global:
  registry: swr.cn-east-2.myhuaweicloud.com
  repository: squids

image:
  pullPolicy: IfNotPresent
  tag: v1.0.0

replicaCount: 1

nodeSelector:
  node-role.kubernetes.io/master: ""

tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  operator: Exists

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: backup-exporter
        topologyKey: kubernetes.io/hostname

resources: {}