apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/name: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_from: {{ .Values.alertmanagerSts.smtp_from }}
      smtp_smarthost: smtpdm.aliyun.com:465
      smtp_hello: "qq.com"
      smtp_auth_username: {{ .Values.alertmanagerSts.smtp_auth_username }}
      smtp_auth_password: {{ .Values.alertmanagerSts.smtp_auth_password }}
      smtp_require_tls: false
    receivers:
    - name: squids
      email_configs:
      - to: {{ .Values.alertmanagerSts.smtp_receiver }}
        send_resolved: false
    route:
      receiver: squids
      group_interval: 5m
      group_wait: 10s
      repeat_interval: 6h
    templates:
    - /etc/alertmanager/*.tmpl