apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-config-tmpl
    namespace: {{.Release.Namespace}}
data:
{{ (.Files.Glob "conf/prometheus.yaml.tmpl").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-rules
    labels:
        name: prometheus-rules
    namespace: {{.Release.Namespace}}
data:
{{ (.Files.Glob "conf/alert-rules.yaml").AsConfig | indent 2 }}