apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-rules
  labels:
    name: thanos-rules
  namespace: {{.Release.Namespace}}
data:
{{ (.Files.Glob "conf/alert-rules.yaml").AsConfig | indent 2 }}
