
objectStorage:
  type: "input these please"
  endpoint: "input these please"
  bucket: "input these please"
  accessKeyId: "input these please"
  accessKeySecret: "input these please"

alertmanagerSts:
  replicaCount: 1
  image:
    registry: swr.cn-east-2.myhuaweicloud.com
    repository: squids
    name: prometheus/alertmanager
    pullPolicy: IfNotPresent
    tag: v0.23.0

  smtp_from: "input these please"
  smtp_auth_username: "input these please"
  smtp_auth_password: "input these please"
  smtp_receiver: "input these please"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "vpc.id"
                operator: In
                values:
                  - "0"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          preference:
            matchExpressions:
              - key: squids/cluster
                operator: In
                values:
                  - squids-monitor
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - alertmanager
          topologyKey: kubernetes.io/hostname

prometheusSts:
  replicaCount: 1
  image:
    registry: swr.cn-east-2.myhuaweicloud.com
    repository: squids
    name: prometheus/prometheus
    pullPolicy: IfNotPresent
    tag: v2.30.3
  pvcSize: 200Gi

  kubePKIPath: /etc/kubernetes/pki

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "vpc.id"
                operator: In
                values:
                  - "0"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          preference:
            matchExpressions:
              - key: squids/cluster
                operator: In
                values:
                  - squids-monitor
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - prometheus
          topologyKey: kubernetes.io/hostname

  prometheus:
    resources: {}
    storage:
      retentionTime: 10d
      minBlockDuration: 2h
      maxBlockDuration: 2h

  thanos:
    resources: {}

thanos:
  image:
    registry: swr.cn-east-2.myhuaweicloud.com
    repository: squids
    name: thanos/thanos
    pullPolicy: IfNotPresent
    tag: v0.23.1

thanosQuery:
  httpPort: 9090
  grpcPort: 10901
  replicaCount: 1

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "vpc.id"
                operator: In
                values:
                  - "0"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          preference:
            matchExpressions:
              - key: squids/cluster
                operator: In
                values:
                  - squids-monitor
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - thanos-query
            topologyKey: kubernetes.io/hostname
          weight: 100

  resources: {}

thanosStore:
  replicaCount: 1
  pvcSize: 10Gi

  affinity:

    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: thanos-store
          topologyKey: kubernetes.io/hostname

  resources: {}

thanosRule:
  replicaCount: 1
  pvcSize: 100Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "vpc.id"
                operator: In
                values:
                  - "0"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          preference:
            matchExpressions:
              - key: squids/cluster
                operator: In
                values:
                  - squids-monitor
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: thanos-rule
          topologyKey: kubernetes.io/hostname

  resources: {}

thanosCompact:
  retention:
    resolutionRaw: 90d
    resolution5m: 180d
    resolution1h: 360d
  pvcSize: 100Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "vpc.id"
                operator: In
                values:
                  - "0"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          preference:
            matchExpressions:
              - key: squids/cluster
                operator: In
                values:
                  - squids-monitor
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - thanos-compact
          topologyKey: kubernetes.io/hostname

  resources: {}

nodeSelector: {}
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists