apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oracle-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oracle-operator
subjects:
  - kind: ServiceAccount
    name: dboperator
    namespace: squids
  - kind: ServiceAccount
    name: dboperator
    namespace: squids-user
