# Default values for apiserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  registry: swr.cn-east-2.myhuaweicloud.com
  repository: squids

image:
  pullPolicy: IfNotPresent
  apiserver:
    tag: v1.0.10
#  qfbbackupjob:
#    tag: v1.0.0

service:
  type: NodePort
  port: 8443
  nodePort: 30443
  healthPort: 80
  healthNodePort: 30442

nodeSelector:
  node-role.kubernetes.io/master: ""

tolerations:
  - effect: NoSchedule
    key: squids/node
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: apiserver
        topologyKey: kubernetes.io/hostname

disableTls: "false"
currentRuntimeEnv: "prod"
