- name: MySQLCluster
  type: MySQL
  groupIntervalMinute: 5
  repeatIntervalMinute: 240
  metrics:
    - name: my-db-hang
    - name: my-execute-count
    - name: my-dml-count
    - name: my-slave-delay
    - name: os-cpu-usage
    - name: os-disk-usage

- name: RedisCluster
  type: Redis
  groupIntervalMinute: 5
  repeatIntervalMinute: 240
  metrics:
    - name: rd-db-hang
    - name: rd-execute-count
    - name: rd-memory-usage
    - name: rd-slave-delay
    - name: os-cpu-usage
    - name: os-disk-usage

- name: SQLServerCluster
  type: SQLServer
  groupIntervalMinute: 5
  repeatIntervalMinute: 240
  metrics:
    - name: ms-db-hang
    - name: ms-execute-count
    - name: ms-dml-count
    - name: ms-slave-delay
    - name: os-cpu-usage
    - name: os-disk-usage


- name: MongoCluster
  type: MongoDB
  groupIntervalMinute: 5
  repeatIntervalMinute: 240
  metrics:
    - name: mg-db-hang
    - name: mg-execute-count
    - name: mg-dml-count
    - name: os-cpu-usage
    - name: os-disk-usage
    - name: mg-slave-delay

- name: ClickhouseCluster
  type: ClickHouse
  groupIntervalMinute: 5
  repeatIntervalMinute: 240
  metrics:
    - name: ch-db-hang
    - name: os-cpu-usage
    - name: os-disk-usage

- name: ElasticSearchCluster
  type: ElasticSearch
  groupIntervalMinute: 5
  repeatIntervalMinute: 240
  metrics:
    - name: os-cpu-usage
    - name: os-disk-usage

- name: MariaDBCluster
  type: MariaDB
  groupIntervalMinute: 5
  repeatIntervalMinute: 240
  metrics:
    - name: my-db-hang
    - name: my-execute-count
    - name: my-dml-count
    - name: my-slave-delay
    - name: os-cpu-usage
    - name: os-disk-usage