apiVersion: v1
kind: ConfigMap
metadata:
  name: squids-license-server
  namespace: {{.Release.Namespace}}
data:
  application-prod.yml: |
    server:
      port: {{ .Values.service.port }}

    spring:
      datasource:
        url: jdbc:mysql://squids-web-mysql-primary-headless:3306/license?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: {{ .Values.mysql.username }}
        password: {{ .Values.mysql.password }}
      redis:
        host: squids-redis-headless # Redis服务器地址
        database: 0 # Redis数据库索引（默认为0）
        port: 6379 # Redis服务器连接端口
        password: # Redis服务器连接密码（默认为空）
        timeout: 300ms # 连接超时时间（毫秒）

    mail-squids:
      mailbox: {{ .Values.mail.mailbox }}
      host: {{ .Values.mail.host }}
      password: {{ .Values.mail.password }}

    moduleService:
      UserModuleGatewayUrl: http://squids-user:29529/api/v1/
      HubModuleGatewayUrl: http://squids-hub:29527/api/v1/
      OperationLogGatewayUrl: http://operation-log:29533/api/v1/
