apiVersion: v1
kind: Service
metadata:
  name: squids-license-server
  namespace: {{.Release.Namespace}}
  labels:
    app: squids-license-server
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: squids-license-server