apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiserver
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: apiserver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiserver
  namespace: {{.Release.Namespace}}-user
  labels:
    app.kubernetes.io/name: apiserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiserver-rbac-{{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: apiserver
subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: {{.Release.Namespace}}
  - kind: ServiceAccount
    name: apiserver
    namespace: {{.Release.Namespace}}-user
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
