apiVersion: v1
kind: ConfigMap
metadata:
  name: squids-backup
  namespace: {{.Release.Namespace}}
data:
  application-prod.yaml: |
    spring:
      datasource:
        url: jdbc:mysql://{{ .Values.mysql.host }}:{{ .Values.mysql.port }}/backup?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: {{ .Values.mysql.username }}
        password: {{ .Values.mysql.password }}
        driver-class-name: com.mysql.cj.jdbc.Driver
      jackson:
        time-zone: GMT+8

      redis:
        host: {{ .Values.redis.host }} # Redis服务器地址
        database: 0 # Redis数据库索引（默认为0）
        port: {{ .Values.redis.port }} # Redis服务器连接端口
        password: # Redis服务器连接密码（默认为空）
        timeout: 300ms # 连接超时时间（毫秒）
    api:
      server:
        port: {{ .Values.apiserver.port }}
      tower:
        port: {{ .Values.tower.port }}
      dbpool:
        port: {{ .Values.dbpool.port }}
    moduleService:
      UserModuleGatewayUrl: http://squids-user:29529/api/v1/
      HubModuleGatewayUrl: http://squids-hub:29527/api/v1/
      OperationLogGatewayUrl: http://{{ .Values.operationLog.host }}:29533/api/v1/