apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-backup
  namespace: {{.Release.Namespace}}
  labels:
    app-name: squids-backup
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app-name: squids-backup
  template:
    metadata:
      labels:
        app-name: squids-backup
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: backup
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.backup.name }}:{{ .Values.image.backup.tag }}
          env:
            - name: APISERVER_CERT_ROOT_PATH
              value: "/grpcserver_tls"
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          volumeMounts:
            - name: timezone
              mountPath: /etc/timezone
            - name: localtime
              mountPath: /etc/localtime
            - name: config-volume
              mountPath: /config
            - name: tls
              mountPath: /grpcserver_tls
      volumes:
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: config-volume
          configMap:
            name: squids-backup
        - name: tls
          secret:
            secretName: grpc-client.tls
            items:
              - key: ca.crt
                path: ca.pem
              - key: tls.crt
                path: client-cert.pem
              - key: tls.key
                path: client-key.pem
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
