apiVersion: v1
kind: ConfigMap
metadata:
  name: inspect-cm
  namespace: bb-system
data:
  inspect-yaml: |
    server:
      name: "inspect.svr"
      ginPprof: false

    db:
      project: "bbm"
      driver: "postgres"
      name: "bobing"
      host: "postgres.bb-system.svc.cluster.local"
      port: "5432"
      user: "bobing"
      password: "bobing"
      charset: "utf8"
      ssl: "disable"
      debug: true

    log:
      level: "DEBUG"
      path: "./logs/"
      name: "bbm.log"
      max_size: 128
      max_age: 7
      max_backups: 30
      to_console: true

    redis:
      hostname:  "redis.bb-system.svc.cluster.local"
      port: 6379
      password: ""
      database: 1

    services:
      bbm_server: "http://bbm.bb-system.svc.cluster.local:9000"
      monitor_server: "http://monitor.bb-system.svc.cluster.local:9002"
      bbc_server: "http://bbc.bb-system.svc.cluster.local:9006"
      audit_bbc_server: "http://bbc.bb-system.svc.cluster.local:9006"
      bomber_bbc_server: "http://bbc.bb-system.svc.cluster.local:9006"


    upload_path: "./upload/images/"
