apiVersion: v1
kind: Service
metadata:
  name: inspect
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: inspect
    app.kubernetes.io/name: inspect
spec:
  type: ClusterIP
  ports:
    - port: 9201
      targetPort: inspect
      protocol: TCP
      name: inspect
  selector:
    app.kubernetes.io/instance: inspect
    app.kubernetes.io/name: inspect