apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  objectstorage.yaml: |
    {{ if .Values.usefilesystem }}
    type: FILESYSTEM
    config:
      directory: {{ .Values.localThanosDir }}
    {{ else }}
    type: {{ .Values.objectStorage.type }}
    config:
      bucket: {{ .Values.objectStorage.bucket }}
      endpoint: {{ .Values.objectStorage.endpoint }}
    {{if eq .Values.objectStorage.type "S3"}}
      access_key: {{ .Values.objectStorage.accessKeyId }}
      secret_key: {{ .Values.objectStorage.accessKeySecret }}
    {{ else if eq .Values.objectStorage.type "ALIYUNOSS" }}
      access_key_id: {{ .Values.objectStorage.accessKeyId }}
      access_key_secret: {{ .Values.objectStorage.accessKeySecret }}
    {{ end }}
    {{ end }}