apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  objectstorage.yaml: |
    type: {{ .Values.objectStorage.type }}
    config:
      bucket: {{ .Values.objectStorage.bucket }}
      endpoint: {{ .Values.objectStorage.endpoint }}
      access_key: {{ .Values.objectStorage.accessKeyId }}
      secret_key: {{ .Values.objectStorage.accessKeySecret }}
