apiVersion: v1
kind: Service
metadata:
  name: squids-dts-proxy-server
  namespace: {{.Release.Namespace}}
  labels:
    app-name: squids-dts-proxy-server
spec:
  type: {{ .Values.service.type}}
  ports:
    - name: proxy
      port: {{ .Values.image.dbmotionProxyServer.containerPort }}
      targetPort: {{ .Values.image.dbmotionProxyServer.containerPort }}
      nodePort: {{ .Values.service.proxyServer.nodeport }}
  selector:
    app-name: squids-dts-proxy-server