apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: notice
    app.kubernetes.io/name: notice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: notice
      app.kubernetes.io/name: notice
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: notice
        app.kubernetes.io/name: notice
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: notice
          image: {{ .Values.global.registry }}/{{ .Values.global.repository}}/{{ .Values.notice.image.name }}:{{.Values.notice.image.tag}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9003
              protocol: TCP
      restartPolicy: Always
