apiVersion: v1
kind: Service
metadata:
  name: notice
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: notice
    app.kubernetes.io/name: notice
spec:
  type: ClusterIP
  ports:
    - port: 9003
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: notice
    app.kubernetes.io/name: notice
