apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbmotion-saas
  namespace: {{ .Release.Namespace }}
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: "In"
              values:
                - squids-syb9zrm0gyqcjfco-1
  storageClassName: local-path
  volumeMode: "Filesystem"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi