#
# dbs-agent deployment template for dbs-api-server use.
# please replace following fields:
#   * metadata.name: dbs-DataSourceId
#   * spec.selector.matchLabels.app: dbs-DataSourceId
#   * spec.template.metadata.labels.app: dbs-DataSourceId
#   * spec.template.spec.nodeSelector:
#       data-source-key: "dbs-DataSourceId"
#       dbsagent: yes 
#  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbs-agent-template
  namespace: {{.Release.Namespace}}-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbs-replace-with-data-source-id
  template:
    metadata:
      labels:
        app: dbs-replace-with-data-source-id
      annotations:
        process.cri/httpProtocol: http
    spec:
      nodeSelector:
        data-source-key: "dbs-replace-with-data-source-id"
        dbsagent: yes
      hostNetwork: true
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      tolerations:
      - key: dbs.woqutech.com/windows
        operator: Exists
        effect: NoSchedule
      - key: "dbs"
        operator: "Exists"
        effect: "NoSchedule"
      - effect: NoExecute
        key: dbs/os
        value: windows
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"

      initContainers:
      - image: {{if eq .Values.verTag "-dev"}}{{.Values.clientImage.dev}}{{else if eq .Values.verTag "-test"}}{{.Values.clientImage.test}}{{else}}{{.Values.clientImage.prod}}{{end}}/qfb-2.0.0.exe:2.0.0
        name: qfb
        command:
        - qfb-2.0.0.exe
        - --help
        env:
        - name: PROCESSCRI_INIT
          value: "true"
      - image: {{if eq .Values.verTag "-dev"}}{{.Values.clientImage.dev}}{{else if eq .Values.verTag "-test"}}{{.Values.clientImage.test}}{{else}}{{.Values.clientImage.prod}}{{end}}/s3fs-2.0.0.exe:2.0.0
        name: s3fs 
        env:
        - name: PROCESSCRI_INIT
          value: "true"
          
      containers:
      - image: {{if eq .Values.verTag "-dev"}}{{.Values.clientImage.dev}}{{else if eq .Values.verTag "-test"}}{{.Values.clientImage.test}}{{else}}{{.Values.clientImage.prod}}{{end}}/dbsagent-2.0.0.exe:2.0.0
        name: dbsagent
        resources: {}
        command:
        - dbsagent-2.0.0.exe
        args:
        - -kubeconfig
        - ../../conf/dbsagent-k8s.conf
        - -config
        - ../../conf/dbsagent.conf
        env:
        - name: QFB_EXE
          value: qfb-2.0.0.exe
        - name: S3FS_EXE
          value: s3fs-2.0.0.exe
      terminationGracePeriodSeconds: 30

