apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dbs-merge-agent
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: dbs-merge-agent
  template:
    metadata:
      labels:
        app: dbs-merge-agent
    spec:
      nodeSelector:
{{/*        node-role.kubernetes.io/master: ""*/}}
        squids/dbs: merger
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
      containers:
      - args:
          - --
          - merge-agent
          - --server=dbs-api-server-internal:8081
        command:
          - tini
        image: {{.Values.images.dbsMergeAgent.registry}}/{{.Values.images.dbsMergeAgent.repository}}/{{.Values.images.dbsMergeAgent.name}}:{{.Values.images.dbsMergeAgent.tag}}{{.Values.verTag}}
        imagePullPolicy: Always
        name: dbs-merge-agent
        resources: {}
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
              - DAC_READ_SEARCH
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /etc/localtime
            name: localtime


