---
# define configmap for db.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-conf
  namespace: {{.Release.Namespace}}
data:
  config.yaml: |
    server:
      port: 8080
      runMode: {{if .Values.verTag}}debug{{else}}release{{end}}
    app:
      eventNamespace: {{.Release.Namespace}}-task
      clientFilePath: {{.Values.clientFilePath}}
      imageRepo: {{if eq .Values.verTag "-dev"}}{{.Values.clientImage.dev}}{{else if eq .Values.verTag "-test"}}{{.Values.clientImage.test}}{{else}}{{.Values.clientImage.prod}}{{end}}
      defaultProjectId: jcjhyisj2tzzlcwk23vexphb7khnpbtc
      squids:
        enable: true
        baseUrl: {{if eq .Values.verTag "-dev"}}{{.Values.squids.webApi.dev}}{{else if eq .Values.verTag "-test"}}{{.Values.squids.webApi.test}}{{else}}{{.Values.squids.webApi.prod}}{{end}}
        appId: dataCommunication
        appSecret: sCvh4X:MsC4A
        credentialKey: 96ff3a77d4a987b193d3c648f1f91453
      logger:
        level: info
        format: json

    database:
      username: {{.Values.metaDb.user}}
      password: {{.Values.metaDb.pwd | quote}}
      host: dbs-meta-mysql
      port: 3306
      database: {{.Values.metaDb.name}}
      debug: false
---
# define service for apiserver
apiVersion: v1
kind: Service
metadata:
  name: dbs-api-server
  namespace: {{.Release.Namespace}}
spec:
  type: NodePort
  selector:
    app: apiserver
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: {{.Values.apiServer.webPort}}
---
# define deployment for apiserver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbs-api-server
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      dnsPolicy: ClusterFirst
      #nodeSelector:
      #  node-role.kubernetes.io/master: ""
      restartPolicy: Always
      securityContext: {}
      serviceAccount: {{.Values.rbac.server.serviceAccount}}
      serviceAccountName: {{.Values.rbac.server.serviceAccount}}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: apiserver
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -config
        - /woqutech/conf/config.yaml
        command:
        - ./apiserver
        image: {{.Values.images.dbsApiServer.registry}}/{{.Values.images.dbsApiServer.repository}}/{{.Values.images.dbsApiServer.name}}:{{.Values.images.dbsApiServer.tag}}{{.Values.verTag}}
        imagePullPolicy: Always
        name: apiserver
        ports:
        - containerPort: 8080
          #hostPort: 18080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /woqutech/conf/
          name: api-server-conf
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /var/woqutech/dbs/install_files
          name: install-files
      volumes:
      - configMap:
          defaultMode: 420
          name: api-server-conf
        name: api-server-conf
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - hostPath:
          path: /var/woqutech/dbs/install_files
          type: ""
        name: install-files
