---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dbs-agent
  namespace: {{.Release.Namespace}}-task
  labels:
    k8s-app: dbs-agent
spec:
  selector:
    matchLabels:
      name: dbs-agent
  template:
    metadata:
      labels:
        name: dbs-agent
      annotations:
        process.cri/httpProtocol: https
    spec:
      nodeSelector:
        woqudbs: "yes"
      hostNetwork: true
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      tolerations:
        - key: dbs.woqutech.com/windows
          operator: Exists
          effect: NoSchedule
        - key: "dbs"
          operator: "Exists"
          effect: "NoSchedule"
        - effect: NoExecute
          key: dbs/os
          value: windows
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoSchedule"
      initContainers:
        - image: {{.Values.dbsInstallServer}}/install_files/qfb-2.0.0.exe:2.0.0
          name: qfb
          command:
            - qfb-2.0.0.exe
            - --help
          env:
            - name: PROCESSCRI_INIT
              value: "true"
        - image: {{.Values.dbsInstallServer}}/install_files/s3fs-2.0.0.exe:2.0.0
          name: s3fs
          env:
            - name: PROCESSCRI_INIT
              value: "true"
      containers:
        - image: {{.Values.dbsInstallServer}}/install_files/dbsagent-2.0.0.exe:2.0.0
          name: dbs-agent
          resources: {}
          command:
            - dbsagent-2.0.0.exe
          args:
            - -kubeconfig
            - "C:/woqutech/dbs/conf/dbsagent-k8s.conf"
            - -config
            - "C:/woqutech/dbs/conf/dbsagent.conf"
          env:
            - name: QFB_EXE
              value: qfb-2.0.0.exe
            - name: S3FS_EXE
              value: "C:/woqutech/dbs/processcri/bin/s3fs-2.0.0.exe"
      terminationGracePeriodSeconds: 30
