---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.server.clusterRole }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - deployments
      - pods
      - pods/log
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.agent.clusterRole }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - '*'