---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.server.serviceAccount }}
  namespace: {{.Release.Namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.server.serviceAccount }}
  namespace: {{.Release.Namespace}}-task
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.agent.serviceAccount }}
  namespace: {{.Release.Namespace}}-task