global:
  registry: swr.cn-east-2.myhuaweicloud.com
  repository: squids

image:
  pullPolicy: IfNotPresent
  tag: v0.1.0

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

resources: {}