apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
  labels:
    app.kubernetes.io/name: redis-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-operator
      vendor: squids
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: redis-operator
      labels:
        app.kubernetes.io/name: redis-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
        vendor: squids
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: redis-operator
      containers:
        - name: operator
          image: {{ .Values.global.registry }}/{{.Values.global.repository}}/redis-operator:{{include "operator.tag" .}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --enable-leader-election
          env:
            - name: CURRENT_RUNTIME_ENV
              value: "{{ .Values.currentRuntimeEnv }}"
            - name: CLUSTER_FORCE_ANTI_AFFINITY
              value: "true"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: logdir
              mountPath: /var/log/operator
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: logdir
          hostPath:
            path: /apps/logs/squids/operator/
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
