apiVersion: v1
kind: ConfigMap
metadata:
  name: operation-log
  namespace: {{.Release.Namespace}}
data:
  application-prod.yml: |
    server:
      port: {{ .Values.service.port }}

    spring:
      datasource:
        url: jdbc:mysql://squids-web-mysql-primary-headless:3306/logdb?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: {{ .Values.mysql.username }}
        password: {{ .Values.mysql.password }}
