apiVersion: v1
kind: Service
metadata:
  name: operation-log
  namespace: {{.Release.Namespace}}
  labels:
    app: operation-log
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: operation-log
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: operation-log
