apiVersion: v1
kind: Service
metadata:
  name: operation-log
  namespace: {{.Release.Namespace}}
  labels:
    app: operation-log
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: operation-log
