apiVersion: v1
kind: ConfigMap
metadata:
  name: squids-hub
  namespace: {{.Release.Namespace}}
data:
  application-prod.yaml: |
    spring:
      datasource:
        url: jdbc:mysql://{{ .Values.mysql.host }}:{{ .Values.mysql.port }}/squids?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: {{ .Values.mysql.username }}
        password: {{ .Values.mysql.password }}
        driver-class-name: com.mysql.cj.jdbc.Driver
      jackson:
        time-zone: GMT+8

      redis:
        host: {{ .Values.redis.host }} # Redis服务器地址
        database: 0 # Redis数据库索引（默认为0）
        port: {{ .Values.redis.port }} # Redis服务器连接端口
        password: # Redis服务器连接密码（默认为空）
        timeout: 300ms # 连接超时时间（毫秒）
      elasticsearch:
        host: {{.Values.elasticsearch.host}}
        port: {{.Values.elasticsearch.port}}
    api:
      server:
        port: {{ .Values.apiserver.port }}
      tower:
        port: {{ .Values.tower.port }}
      dbpool:
        port: {{ .Values.dbpool.port }}
    pool:
      init:
        auto: {{.Values.pool.autoInit}}
      expand:
        auto: {{.Values.pool.autoExpand}}
      charge:
        type: {{.Values.pool.chargeType}}

    moduleService:
      UserModuleGatewayUrl: http://squids-user:29529/api/v1/
      TradeModuleGatewayUrl: http://squids-trade:29528/api/v1/
      BackupEndpointUrl: http://squids-backup:29531/api/v1/
      OperationLogGatewayUrl: http://{{ .Values.operationLog.host }}:29533/api/v1/
      phoenixEndpoint: http://{{ .Values.phoenix.domain}}:9091/phoenix/api/v2/
      DmsModuleGatewayUrl: http://{{ .Values.dms.domain}}:8999/bbm/dms/v1/
      LicenseServerModuleGatewayUrl: {{ .Values.licenseServer.url }}
      dtsEndpoint: http://{{ .Values.dts.domain}}:31000/api/v2/
      dbsEndpoint: http://{{ .Values.dbs.domain}}:30080/api/v1/

    sms:
      credential:
        keySecret: {{.Values.sms.credential.keySecret}}

    data-flashback-task:
      default:
        days: {{.Values.dataFlashbackTask.default.days}}

    credential:
      provider:
        aliYun:
          keyId: {{.Values.credential.aliYun.keyId}}
          keySecret: {{.Values.credential.aliYun.keySecret}}