apiVersion: v1
kind: ConfigMap
metadata:
  name: squidshub
  namespace: squids
data:
  application-prod.properties: |
    # datasource
    spring.datasource.url=jdbc:mysql://squids-web-mysql-primary-headless:3306/squids?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    spring.datasource.username={{ .Values.mysql.username }}
    spring.datasource.password={{ .Values.mysql.password }}
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    
    modulservice.UserModulGatewayUrl=http://squidsuser-headless:29529/api/v1
    modulservice.TradeModulGatewayUrl=http://localhost:7001/api/v1

    spring.redis.host=squids-redis-headless
    spring.redis.database=0
    spring.redis.port=6379
    spring.redis.password=
    spring.redis.timeout=300ms