apiVersion: v1
kind: Service
metadata:
  name: squidshub
  namespace: {{ .Release.Name }}
  labels:
    app-name: squidshub
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app-name: squidshub