global:
  registry: swr.cn-east-2.myhuaweicloud.com
  repository: squids

replicaCount: 1

image:
  name: kibana
  pullPolicy: IfNotPresent
  tag: 6.4.1

nameOverride: ""
fullnameOverride: ""

service:
  nodePort: 30064

resources: {}

nodeSelector: {}
tolerations:
  - effect: NoSchedule
    key: squids/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "vpc.id"
              operator: In
              values:
                - "0"
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        preference:
          matchExpressions:
            - key: squids/cluster
              operator: In
              values:
                - squids-monitor
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: kibana
        topologyKey: kubernetes.io/hostname

esurl: http://elasticsearch-logging:9200
