apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 5601
      protocol: TCP
      targetPort: 5601
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "kibana.selectorLabels" . | nindent 4 }}
