apiVersion: v1
kind: Service
metadata:
  name: squids-console
  namespace: {{.Release.Namespace}}
  labels:
    app-name: squids-console
spec:
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
    {{ if eq .Values.env "pro" }}
    - port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.port }}
      protocol: TCP
      name: https
    {{ end }}
    {{ if .Values.enableWeb }}
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: console
    {{ end }}
  selector:
    app-name: squids-console
