apiVersion: apps/v1
kind: Deployment
metadata:
  name: squids-console
  namespace: {{.Release.Namespace}}
  labels:
    app-name: squids-console
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app-name: squids-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app-name: squids-console
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: squids-console
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          image:  {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.console.name }}:{{ .Values.image.console.tag }}
          ports:
            - containerPort: {{ .Values.containers.http.containerPort}}
              hostPort: {{ .Values.containers.http.containerPort}}
            {{ if eq .Values.env "pro" }}
            - containerPort: {{ .Values.containers.ssl.containerPort}}
              hostPort: {{ .Values.containers.ssl.containerPort}}
            {{ end }}
            {{ if .Values.enableWeb }}
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 18081
              hostPort: 18081
            {{ end }}
          volumeMounts:
            - name: timezone
              mountPath: /etc/timezone
            - name: localtime
              mountPath: /etc/localtime
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: squids-console-config
              mountPath: /usr/share/nginx/html/config
            - name: geoip
              mountPath: /etc/nginx/geoip
            {{ if eq .Values.env "pro" }}
            - name: cert
              mountPath: /etc/nginx/cert
            {{ end }}
            - name: dbs-cert
              mountPath: /etc/nginx/dbs-cert
      volumes:
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: config-volume
          configMap:
            name: nginx-conf
        - name: squids-console-config
          configMap:
            name: squids-console-config
        - name: geoip
          hostPath:
            path: /squids-data/install/nginx/GeoIP
        {{ if eq .Values.env "pro" }}
        - name: cert
          secret:
            secretName: sslca
            items:
              - key: squids.crt
                path: squids.crt
              - key: squids.key
                path: squids.key
        {{ end }}
        - configMap:
            defaultMode: 420
            name: dbs-gserver-cert
          name: dbs-cert
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}