apiVersion: v1
kind: ConfigMap
metadata:
  name: squids-console-config
  namespace: {{.Release.Namespace}}
data:
  root.config.json: |
    {
      "grafanaBaseurl": "{{.Values.grafana.url.rds}}",
      "dtsGrafanaBaseurl": "{{.Values.grafana.url.dts}}",
      "webUrl": "{{.Values.web.url}}"
    }
