apiVersion: v1
kind: ConfigMap
metadata:
  name: squids-console-config
  namespace: squids
data:
  root.config.json: |
    {
      "grafanaBaseurl": "{{.Values.grafana.url}}",
      "webUrl": "{{.Values.web.url}}"
    }
