apiVersion: v1
kind: ConfigMap
metadata:
  name: dbs-gserver-cert
  namespace: {{.Release.Namespace}}
data:
  server.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAry1PeUYTEoXV+qK7dh5pcwGwm03U5/cRZCo20QCmaa10og/z
    CLsZOSgIJGA7e8fsTWLsvIgfj7g35mSQOeEhiYauIYWl+/l3pIit1YSUivw4HjrY
    V+eMZQbNl6xhJhuFyaWxNY7KVAaUv4X5vxQ3lryTRrERIwCl1awaQkSl26HYj7V+
    wGVdEeW3H2NDhq7+mjAogHLarpcWO4K0VKC8Hm2LTNkY6URKXN2MBfwMdsXIRa8u
    93PXjlgzZC+ijOfhslPuZGRjr7gP8chQQkYvn7ErxYkqZTJ/zkTc8G4ieJDCsYkb
    E4MzCm0YHLemljDRl/RyhqpvthVcesNxJWJAMQIDAQABAoIBAE7nGsfmH0sVi1cU
    G1nNwvNxTGn3ebFt4KB8PyqOn2Y0IbepdW92TpsnA9vWmJRdbXtB1p3otkaW1F7q
    5uebFu8KAb7JowTGzfQHOD1XNU0Q4/oByVZ2zg7nLI1nsG5osS8teY9FHK8SM8e8
    gcxmP8+earvJn41jik6e8UjuAMLW+ZltGIyKS3OKltRSc/bGaLIEEuoawOqBBiqI
    nibK9CCSm0gcbP7lTLYDk3fUAHUpVeKqV9m/Tj2VXwjHeOZVHCv1NqFOAYdJGNOe
    I8Vtrp9N5R0SelguEHsTNRZpXADv1gRLuBIbh1bq/Mfai464V/95kz97jLf87AQl
    nGMk/h0CgYEA1sW53K0XXBjotIXfkQwz2rIZvFg9L7REoP2Ndh4YuanLcj2HeH80
    3CH7EpTyjbGmcopLpZVvvTkeCtxWNClgw5GlLkz46iD+lZ31ktkq7MzLs061pGFR
    Fl5OUY4xQ0Jmzr80OAKoF5hyO7oZmYTpTR8cGWP6GGKuDzBlvQp3r3cCgYEA0M3N
    Kq1e8x/OOC2rwtdb5fTCizhRL2cgVaBZF0MEwzHXQI5qRcj+iBIsjLd8yIkuQnh6
    uxVgePVOKzfBaVfYlOdsmdvwakqmSybz3XEAyuBRFR9RGsi9cRgHH+kFIYSdmXmm
    JxW3RODESceutz5KNVaRH9PyA+s5r2aJgwNOh5cCgYBRNdDSxcyYcX7Ei/5+bTvK
    TR/4HPF98U8mBNoRuM2mnrKkDuoDwS3usxap7xJMS8lhdDOod/oZddiLSMd7z82c
    BZ2NBWP1u+YoEuOB1IYrpkC8G14JuxabO6unoPm1sg0HzjrjlvWSfn1rYjI934kM
    NWA9pZUy1VV1vtopgiTBfwKBgQDJ93bPI/kmk4olvs9X3HWQfWo7vZKRll+pUzs5
    i+KsZ6Y8VESpEZxZw7KBve2eD0rGksCr+yZgeW5N0VVsbsMYbK0YOaxXM7OcF6Zk
    eCx7D/R9yNfrX2YWYVZq4DrNS/gg/pDfV1r47awPbW0q475lz0D6l0iNz9XxOe4i
    4mzwKwKBgA6kvpDfWa0qzcPg75aR9F2Ls5b+0BP2EBmsqAqrWAPVUBJ5Wyx/Xv6A
    EpRhu2yZbPwnfIpYGH0prTfffD/qX3amXJMmZ6370ttAnyWt3bJSLIS9qhxiIX1U
    Xn1TwVkpLlIopyWRHsaScDUHPhfaO0L1Gl7EYZZxlqw9TA5rEl7l
    -----END RSA PRIVATE KEY-----
  server.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDxjCCAa6gAwIBAgIUdZlJy+xlLmEKsxiBw1hvAqkzewIwDQYJKoZIhvcNAQEL
    BQAwDTELMAkGA1UEBwwCQ04wHhcNMjIxMTIzMDQ0NjI1WhcNMzIxMTIwMDQ0NjI1
    WjANMQswCQYDVQQHDAJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    AK8tT3lGExKF1fqiu3YeaXMBsJtN1Of3EWQqNtEApmmtdKIP8wi7GTkoCCRgO3vH
    7E1i7LyIH4+4N+ZkkDnhIYmGriGFpfv5d6SIrdWElIr8OB462FfnjGUGzZesYSYb
    hcmlsTWOylQGlL+F+b8UN5a8k0axESMApdWsGkJEpduh2I+1fsBlXRHltx9jQ4au
    /powKIBy2q6XFjuCtFSgvB5ti0zZGOlESlzdjAX8DHbFyEWvLvdz145YM2Qvoozn
    4bJT7mRkY6+4D/HIUEJGL5+xK8WJKmUyf85E3PBuIniQwrGJGxODMwptGBy3ppYw
    0Zf0coaqb7YVXHrDcSViQDECAwEAAaMeMBwwGgYDVR0RBBMwEYIJbG9jYWxob3N0
    hwR/AAABMA0GCSqGSIb3DQEBCwUAA4ICAQCFU19rXUJS81xgTYYrTbiO/qz2NCGs
    WwxtpIujnc8lNA4UmOEdIMvvlGtNgIjOhnMOXNNDimUDgBkukjioma4liSGfDjU4
    EmkNhnNNmOCQIhOE6l2bsiD6L3lt8YvjTsReF8VYRm877nbGFhHaXPzTpP7b6VwO
    +k6ayCVtQ0FyxVIXeqcJO0/XO5fE8KY4m7URLZthKzQyBfqs7l0MYJVHGMN3z1sv
    DjwoL8Nh2LRF4Y9oIwuaIdMDxgvP+ciKy2yXwDaV8j66epS8brGZRyxctGhxniV4
    6sMUiKi2KQkbiWRzUmepOi1ehgjdL/DQcswuGIhK/55LoiCImSMMrEUVJVIQEoyS
    YQcuMh3DBdwJC6BUetkj/vBNWisjb8y1XsISYR7VV2eV2G2pvhdWFuHAXv46QwJD
    hJuPDiIPhqr6GXQSzgw2o1opOAPX6ycVED6P8FYTspPfyM95AOREJI6JIy5jSTPb
    0gtRFehus4o6Kw/M+ItpXrNGlUCldRVyEkJzFS9RhmShC87nPclwuSkCjYUc7vP/
    vHffPcSbgGI5EUMm67MhC41gKIXPkaL+d42XEhnoiHP0XAZIsc6IqgVE/VjFnt9R
    tcgejvsjGsDttvG3UAgW9uEy75PMNn/pn/yj5892yQdT42NgcAUv3I2JuYyyURsO
    bn8D6MJaMFKfIQ==
    -----END CERTIFICATE-----