apiVersion: v1
kind: Service
metadata:
  name: squids-cloud-site-headless
  namespace: squids
  labels:
    app-name: squids-cloud-site
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app-name: squids-cloud-site
