{{ if .Values.enableWeb }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squids-web
  namespace: {{.Release.Namespace}}
  labels:
    app-name: squids-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app-name: squids-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app-name: squids-web
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: squids-web
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          image:  {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.web.name }}:{{ .Values.image.web.tag }}
          ports:
            - containerPort: {{ .Values.containers.web.containerPort}}
          volumeMounts:
            - name: timezone
              mountPath: /etc/timezone
            - name: localtime
              mountPath: /etc/localtime
            - name: squids-web-config
              mountPath: /app/apps/web/public/config
      volumes:
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: squids-web-config
          configMap:
            name: squids-web-config
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
