# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
global:
  registry: swr.cn-east-2.myhuaweicloud.com
  repository: squids

tag: latest
enablePMMClient: false
image:
  pullPolicy: IfNotPresent
  name: strimzi-operator
  tag: 0.28.0


nodeSelector:
  node-role.kubernetes.io/master: ""

tolerations:
  - effect: NoSchedule
    key: squids/node
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: kafka-operator
        topologyKey: kubernetes.io/hostname