apiVersion: v1
kind: Service
metadata:
  name: {{ include "conn-pool.fullname" . }}
  namespace: bb-system
  labels:
    {{- include "conn-pool.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "conn-pool.selectorLabels" . | nindent 4 }}
