# Default values for squids-hub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: Always
  dbmotionSassServer:
    registry: docker.io
    repository: squids
    name: squids-dbmotion-saas-server
    tag: dev
    containerPort: 3000
  dbmotion:
    registry: docker.io
    repository: squids
    name: squids-dbmotion-tool

service:
  type: ClusterIP
  port: 3000


# env: test pro
env: test

mysql:
  host: squids-web-mysql-primary-headless.squids.svc.cluster.local
  port: "3306"
  username: squidsRoot9527
  # !!!!!!! helm upgrade 的时候再填写真实密码，不要提交真实密码到 git 仓库 !!!!!!!!
  # !!!!!!! helm upgrade 的时候再填写真实密码，不要提交真实密码到 git 仓库 !!!!!!!!
  # !!!!!!! helm upgrade 的时候再填写真实密码，不要提交真实密码到 git 仓库 !!!!!!!!
  password: password_placeholder
  # !!!!!!! helm upgrade 的时候再填写真实密码，不要提交真实密码到 git 仓库 !!!!!!!!
  # !!!!!!! helm upgrade 的时候再填写真实密码，不要提交真实密码到 git 仓库 !!!!!!!!
  # !!!!!!! helm upgrade 的时候再填写真实密码，不要提交真实密码到 git 仓库 !!!!!!!!
es:
  url: http://elasticsearch-logging.squids-logging.svc.cluster.local:9200

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "squids-dbmotion-saas-server"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "vpc.id"
              operator: In
              values:
                - "0"
