apiVersion: v1
kind: ConfigMap
metadata:
  name: squids-trade
  namespace: {{.Release.Namespace}}
data:
  application-prod.yml: |
    server:
      port: {{ .Values.service.port }}

    spring:
      datasource:
        url: jdbc:mysql://squids-web-mysql-primary-headless:3306/tradedb?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=UTC
        username: {{ .Values.mysql.username }}
        password: {{ .Values.mysql.password }}
      redis:
        host: squids-redis-headless # Redis服务器地址
        database: 0 # Redis数据库索引（默认为0）
        port: 6379 # Redis服务器连接端口
        password: # Redis服务器连接密码（默认为空）
        timeout: 300ms # 连接超时时间（毫秒）

    {{ if eq .Values.env "pro" }}
    paypal-config:
      clientId: {{ .Values.paypal.clientId }}
      clientSecret: {{ .Values.paypal.clientSecret }}
      cancelUrl: https://squids.cn
      returnUrl: http://squids.cn/api/v1/tradeRechargeOrder/paySuccess

    pay:
      success: https://squids.cn/
      fail: https://squids.cn/

    pdf:
      logo_url: https://squis.cn/assets/logo.png
    {{ end }}

    {{ if eq .Values.env "test" }}
    paypal-config:
      clientId: {{ .Values.paypal.clientId }}
      clientSecret: {{ .Values.paypal.clientSecret }}
      cancelUrl: http://{{.Values.server.host}}
      returnUrl: http://{{.Values.server.host}}/api/v1/tradeRechargeOrder/paySuccess

    pay:
      success: {{.Values.server.host}}
      fail: {{.Values.server.host}}

    pdf:
      logo_url: http://{{.Values.server.host}}/assets/logo.png
    {{ end }}


    moduleService:
      UserModuleGatewayUrl: http://squids-user:29529/api/v1/
      HubModuleGatewayUrl: http://squids-hub:29527/api/v1/

    charging-config:
      discount: 0.7
      givemoney: 3000
      overdueTime: 7
      disableTime: 14

    mail-squids:
      mailbox: {{ .Values.mail.mailbox }}
      host: {{ .Values.mail.host }}
      password: {{ .Values.mail.password }}