apiVersion: v1
kind: ConfigMap
metadata:
  name: squids-trade
  namespace: squids
data:
  application-prod.yml: |
    server:
      port: {{ .Values.service.port }}

    spring:
      datasource:
        url: jdbc:mysql://squids-web-mysql-primary-headless:3306/tradedb?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: {{ .Values.mysql.username }}
        password: {{ .Values.mysql.password }}
        druid:
          initial-size: 5 #连接池初始化大小
          min-idle: 10 #最小空闲连接数
          max-active: 100 #最大连接数
          web-stat-filter:
            exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
          stat-view-servlet: #访问监控网页的登录用户名和密码
            login-username: druid
            login-password: druid


      redis:
        host: squids-redis-headless # Redis服务器地址
        database: 0 # Redis数据库索引（默认为0）
        port: 6379 # Redis服务器连接端口
        password: # Redis服务器连接密码（默认为空）
        timeout: 300ms # 连接超时时间（毫秒）

    {{ if eq .Values.env "pro" }}
    paypal-config:
      clientId: {{ .Values.paypal.clientId }}
      clientSecret: {{ .Values.paypal.clientSecret }}
      cancelUrl: https://squids.io
      returnUrl: https://squids.io/api/v1/tradeRechargeOrder/paySuccess

    pay:
      success: https://squids.io/
      fail: https://squids.io/
    {{ end }}

    {{ if eq .Values.env "test" }}
    paypal-config:
      clientId: {{ .Values.paypal.clientId }}
      clientSecret: {{ .Values.paypal.clientSecret }}
      cancelUrl: {{.Values.server.host}}
      returnUrl: {{.Values.server.host}}/api/v1/tradeRechargeOrder/paySuccess

    pay:
      success: {{.Values.server.host}}
      fail: {{.Values.server.host}}
    {{ end }}


    moduleService:
      UserModuleGatewayUrl: http://squidsuser-headless:29529/api/v1/
      HubModuleGatewayUrl: http://squidshub-headless:29527/api/v1/

    charging-config:
      discount: 0.7
      givemoney: 3000
      overdueTime: 7
      disableTime: 14

    mail-squids:
      mailbox: {{ .Values.mail.mailbox }}
      host: {{ .Values.mail.host }}
      password: {{ .Values.mail.password }}