apiVersion: v1
kind: Service
metadata:
  name: squidstrade-headless
  namespace:  {{ .Release.Name }}
  labels:
    app: squids-trade
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: squids-trade
