apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{.Release.Namespace}}
data:
  grafana.ini: |
{{ if .Values.grafana.enableHttps }}
    {{ range .Files.Lines "config/grafana.ini" }}
    {{ . }}{{ end }}
{{ else }}
    {{ range .Files.Lines "config/grafana-http.ini" }}
    {{ . }}{{ end }}
{{ end }}

---
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: {{.Release.Namespace}}
apiVersion: v1
data:
  dashboards.yaml: |-
    # # config file version
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        folderUid: ''
        type: file
        options:
          path: /var/lib/grafana/dashboards

  datasources.yaml: |-
    # # config file version
    apiVersion: 1
    # # list of datasources to insert/update depending
    # # on what's available in the database
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus.{{.Release.Namespace}}.svc.cluster.local:9090
        # <bool> enable/disable basic auth
        basicAuth: false
        # <bool> enable/disable with credentials headers
        withCredentials: false
        # <bool> mark as default datasource. Max one per org
        isDefault: true
        version: 2
        # <bool> allow users to edit datasources from the UI.
        editable: true