apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbmotion-saas
  namespace: {{ .Release.Namespace }}-user
spec:
  storageClassName: local-path
  volumeMode: "Filesystem"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 36Gi