apiVersion: apps/v1
kind: Deployment
metadata:
  name: squids-dbmotion-saas-server
  namespace: {{.Release.Namespace}}
  labels:
    app-name: squids-dbmotion-saas-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app-name: squids-dbmotion-saas-server
  template:
    metadata:
      labels:
        app-name: squids-dbmotion-saas-server
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: dbmotion-saas
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.image.dbmotionSassServer.registry }}/{{ .Values.image.dbmotionSassServer.repository }}/{{ .Values.image.dbmotionSassServer.name }}:{{ .Values.image.dbmotionSassServer.tag }}
          env:
            - name: SERVER_MODE
              value: "SAAS"
            - name: K8S_NAMESPACE
              value: "squids-user"
            - name: NODE_SELECTOR_KEY
              value: "squids/cluster"
            - name: NODE_SELECTOR_VALUE
              {{ if .Values.enableDbmotionNode }}
              value: "squids-dbmotion"
              {{ else }}
              value: "squids-master"
              {{ end }}
            - name: DBMOTION_IMAGE
              value: {{ .Values.image.dbmotion.registry }}/{{ .Values.image.dbmotion.repository }}/{{ .Values.image.dbmotion.name }}:{{ .Values.image.dbmotion.tag }}
            - name: MYSQL_HOST
              value: {{ .Values.mysql.host }}
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER_NAME
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: JWT_SECRET
              value: squids_secret_xz98fj9r1wq
            - name: ELASTICSEARCH_URI
              value: {{ .Values.es.url }}
            - name: PVC_CLAIM_NAME
              value: dbmotion-saas
            - name: MASTER_TOLERATION
              value: "y"
            - name: CPU_REQUEST
              value: "500m"
            - name: CPU_LIMIT
              value: "4"
            - name: MEMORY_REQUEST
              value: "100Mi"
            - name: MEMORY_LIMIT
              value: "8Gi"
          ports:
            - name: dbmotion-saas
              containerPort: {{ .Values.image.dbmotionSassServer.containerPort }}
          volumeMounts:
            - name: timezone
              mountPath: /etc/timezone
            - name: localtime
              mountPath: /etc/localtime
            - mountPath: /dbmotion/log
              name: log-volume
      volumes:
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: log-volume
          persistentVolumeClaim:
            claimName: dbmotion-sass-log
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbmotion-sass-log
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local-path
  volumeMode: "Filesystem"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
