apiVersion: v1
kind: Service
metadata:
  name: squids-dbmotion-saas-server
  namespace: {{.Release.Namespace}}
  labels:
    app-name: squids-dbmotion-saas-server
spec:
  type: {{ .Values.service.type}}
  ports:
    - port: {{ .Values.image.dbmotionSassServer.containerPort }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }}
  selector:
    app-name: squids-dbmotion-saas-server