apiVersion: mysql.squids.io/v1
kind: MysqlCluster
metadata:
  labels:
    app-name: squids-dbmotion-mysql
    squids.io/db-type: mysql
  name: squids-dbmotion-mysql
  namespace: squids
spec:
  clusterSpec:
    backupImage: swr.cn-east-2.myhuaweicloud.com/squids/qfb-mysql-5.7:v1.0.0
    image: swr.cn-east-2.myhuaweicloud.com/squids/mysql:5.7.26
    leaderImage: swr.cn-east-2.myhuaweicloud.com/squids/mysqlleader:v1.0.0
    matchLabels:
      app-name: squids-dbmotion-mysql
      squids.io/db-type: mysql
    mode: HACluster
    nodeAffinityStrategies:
      - key: squids/cluster
        operator: In
        values:
          - "squids-master"
    restoreImage: swr.cn-east-2.myhuaweicloud.com/squids/qfb-mysql-5.7:v1.0.0
    version: "5.7"
  databaseResource:
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi
    storage:
      iops: -1
      size: 10737418240
  replicas: 1
  slaveReplicas: 0
