imagePullSecrets:
  - name: dbsinan-image-puller

imageCredentials:
  registry: registry.cn-hangzhou.aliyuncs.com/dbsinan
  username: xxx
  password: xxx

global:
  registry: registry.cn-hangzhou.aliyuncs.com
  repository: dbsinan

bbNginx:
  image:
    name: nginx
    tag: w1.8
bbm:
  image:
    name: bbm
    tag: w1.8
bbmFile:
  image:
    name: bbm-file
    tag: w1.4
connPool:
  image:
    name: conn-pool
    tag: w1.8
inspect:
  image:
    name: inspect
    tag: w1.8
monitor:
  image:
    name: monitor
    tag: v1.0
notice:
  image:
    name: notice
    tag: v1.0
postgres:
  image:
    name: postgres
    tag: 9.6-bb
sqlExporter:
  image:
    name: sql-exporter
    tag: w1.7
sshExporter:
  image:
    name: ssh-exporter
    tag: v1.0
woquAdapter:
  image:
    name: woqu-adapter
    tag: w1.4