# Default values for backup-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
global:
  registry: swr.cn-east-2.myhuaweicloud.com
  repository: squids

tag: latest
# current operator version
image:
  pullPolicy: IfNotPresent
  operator:
    tag: v0.0.1

nodeSelector:
  node-role.kubernetes.io/master: ""

tolerations:
  - effect: NoSchedule
    key: squids/node
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: middleware-operator
        topologyKey: kubernetes.io/hostname

resources:
  requests:
    cpu: "500m"
    memory: "200Mi"
  limits:
    cpu: "4000m"
    memory: "400Mi"

serviceAccount: middleware-operator
clusterRole: middleware-operator
clusterRoleBinding: middleware-operator

# dev | test | prod
currentRuntimeEnv: "prod"
# prod 环境版本号
jobImageVersion: "v1.0.0"