apiVersion: v1
kind: ConfigMap
metadata:
  name: hubble-ca-cert
  namespace: {{.Release.Namespace}}
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDJzCCAg+gAwIBAgIQPd3cyT8k+mJMEdKyKi6x1TANBgkqhkiG9w0BAQsFADAe
    MRwwGgYDVQQDExNodWJibGUtY2EuY2lsaXVtLmlvMB4XDTIxMDQxNDEwNDMzM1oX
    DTI0MDQxMzEwNDMzM1owHjEcMBoGA1UEAxMTaHViYmxlLWNhLmNpbGl1bS5pbzCC
    ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALXY6wj65wtPpvwQj5dDcfVR
    6PeaNnd3amzhLsXl75aEI6/56Rjy6bt5uVIhY/D/m4YYm/pCGNLJkCsRYmgrjcpm
    HSWjK0L7bbcOOkxkkPq16Uuzt2brwZQ6TBUeIFF39i7QvzlNZIxX/g6LTrXLxydW
    TEybGkvZ357xel3xIpVWMySpaRXSLB0copnPVyLMbyErYE0w/CpHb0FSKEE4oKwk
    YiRd2vaWfGz1RQbkszC/UAGtmiSDhDCZgAINC4VD3baWvsM6w/ky5fguZJHrASOQ
    kD/ZPKnzG4nABZNswRT/2y+pnE2E78t1SKm0nLL+qUUmg7RZ0Jmnxh0NOFwFJ8kC
    AwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
    BgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTUhedRQxX/vWDN7cNS
    a4pszNsFUTANBgkqhkiG9w0BAQsFAAOCAQEAcWLUbnk0i51OUnmWS2Qm/GdAxqx+
    p4nBhrLIoPbe9EMnYAfNxXNVIsCeywlTHDPBugz83ZpAAoaz4UNVanxP+10nmPtb
    ptD6A/bu6TWF33k2YJq9BRPnHQwTaD76LjNISfIoi/9pOiysJuShBlvHHMVtuL3F
    PJ0nlCiDO8APSIJE2Dlb0nC/WztScH7wzsB8ZGvWBavZoUI87bOxLXW0vVfvb/cn
    yxke+2dUTTcpD2B4f98DDG88Iqu8eFoAEbFqf8xl7Fi5/sANWgmKcEMgThFMQYXd
    LxdmzYQ2BodRPXEy8EDhIHSKHVMkJtF0mNuykRFuYN8VoXILQFngn+pfrA==
    -----END CERTIFICATE-----