apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: bb-system
  name: pv-bb-postgres
spec:
  capacity:
    storage: 500Gi
  hostPath:
    path: "/squids-data/local-path-provisioner/pvc-13c82f55-9d02-4154-875c-96dfe5ad3e51_bb-system_pvc-bb-postgres"
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem

