---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-exporter
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-exporter-default
rules:
  - apiGroups: ["*"]
    resources:
      - "*"
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-exporter-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backup-exporter-default
subjects:
  - kind: ServiceAccount
    name: backup-exporter
    namespace: {{.Release.Namespace}}
---
apiVersion: v1
kind: Service
metadata:
  name: backup-exporter
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: backup-exporter
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app.kubernetes.io/name: backup-exporter
    app.kubernetes.io/instance: RELEASE-NAME
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-exporter
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: backup-exporter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: backup-exporter
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backup-exporter
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: "backup-exporter"
      containers:
        - name: backup-exporter
          image: {{.Values.global.registry }}/{{.Values.global.repository}}/squids-exporter:{{.Values.image.tag}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--collector.Backup"
            - --log.level=debug
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
