apiVersion: apps/v1
kind: Deployment
metadata:
  name: squids-dbpool
  labels:
    app.kubernetes.io/name: squids-dbpool
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: squids-dbpool
      vendor: squids
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: squids-dbpool
      labels:
        app.kubernetes.io/name: squids-dbpool
        app.kubernetes.io/instance: {{ .Release.Name }}
        vendor: squids
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: squids-dbpool
      containers:
        - name: squids-dbpool
          image: {{ .Values.global.registry }}/{{.Values.global.repository}}/squids-dbpool:{{ .Values.image.squidsdbpool.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /squids-dbpool
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUG
              value: "true"
            - name: DISABLE_TLS
              value: "{{ .Values.disableTls }}"
            - name: CURRENT_RUNTIME_ENV
              value: "{{ .Values.currentRuntimeEnv }}"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: logdir
          hostPath:
            path: /apps/logs/squids/operator/
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
