apiVersion: v1
kind: ServiceAccount
metadata:
  name: squids-dbpool
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: squids-dbpool
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: squids-dbpool
  namespace: {{.Release.Namespace}}-user
  labels:
    app.kubernetes.io/name: squids-dbpool
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: squids-dbpool-rbac-{{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: squids-dbpool
subjects:
  - kind: ServiceAccount
    name: squids-dbpool
    namespace: {{.Release.Namespace}}
  - kind: ServiceAccount
    name: squids-dbpool
    namespace: {{.Release.Namespace}}-user
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
