apiVersion: v1
kind: Service
metadata:
  name: squids-dbpool
  labels:
    app.kubernetes.io/name: squids-dbpool
    vendor: squids
spec:
  selector:
    app.kubernetes.io/name: squids-dbpool
    vendor: squids
  type: {{ .Values.service.type }}
  sessionAffinity: None
  ports:
    - name: squids-dbpool
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9999
      {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- end }}
    - name: squids-dbpool-health
      protocol: TCP
      port: {{ .Values.service.healthPort }}
      targetPort: 80
      {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
      {{- if .Values.service.healthNodePort }}
      nodePort: {{ .Values.service.healthNodePort }}
      {{- end }}
    {{- end }}
    - name: metrics
      port: 8080
