{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: node-exporter*/}}
{{/*  namespace: {{.Release.Namespace}}*/}}
{{/*  annotations:*/}}
{{/*    prometheus.io/scrape: "true"*/}}
{{/*  labels:*/}}
{{/*    kubernetes.io/cluster-service: "true"*/}}
{{/*    addonmanager.kubernetes.io/mode: Reconcile*/}}
{{/*    kubernetes.io/name: "NodeExporter"*/}}
{{/*spec:*/}}
{{/*  clusterIP: None*/}}
{{/*  ports:*/}}
{{/*    - name: metrics*/}}
{{/*      port: 9100*/}}
{{/*      protocol: TCP*/}}
{{/*      targetPort: 9100*/}}
{{/*  selector:*/}}
{{/*    k8s-app: node-exporter*/}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: {{.Release.Namespace}}
  labels:
    k8s-app: node-exporter
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    version: v1.0.0
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
      version: v1.0.0
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        k8s-app: node-exporter
        version: v1.0.0
    spec:
      priorityClassName: system-node-critical
      containers:
        - name: prometheus-node-exporter
          image: prom/node-exporter:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--path.rootfs=/host"
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - mountPath: /host
              name: host
              readOnly: true
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
      hostNetwork: true
      hostPID: true
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: host
          hostPath:
            path: /
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}