apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-cm
  namespace: bb-system
data:
  monitor-yml: |
    global:
      scrape_interval: 1m
      scrape_timeout: 1m
      evaluation_interval: 10s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - notice.bb-system.svc.cluster.local:9003
        scheme: http
        timeout: 10s
    rule_files:
    - rules/*.yml
    scrape_configs:
    - job_name: interval10s
      scrape_interval: 10s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
      - files:
        - ./servers/*10s.json
        refresh_interval: 5m
      relabel_configs:
      - source_labels: [instance]
        separator: ;
        regex: instance-(.*)
        target_label: __param_id
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __param_interval
        replacement: 10s
        action: replace
    - job_name: interval30s
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
      - files:
        - ./servers/*30s.json
        refresh_interval: 5m
      relabel_configs:
      - source_labels: [instance]
        separator: ;
        regex: instance-(.*)
        target_label: __param_id
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __param_interval
        replacement: 30s
        action: replace
    - job_name: interval1m
      scrape_interval: 1m
      scrape_timeout: 1m
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
      - files:
        - ./servers/*1m.json
        refresh_interval: 5m
      relabel_configs:
      - source_labels: [instance]
        separator: ;
        regex: instance-(.*)
        target_label: __param_id
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __param_interval
        replacement: 1m
        action: replace
    - job_name: interval5m
      scrape_interval: 5m
      scrape_timeout: 1m
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
      - files:
        - ./servers/*5m.json
        refresh_interval: 5m
      relabel_configs:
      - source_labels: [instance]
        separator: ;
        regex: instance-(.*)
        target_label: __param_id
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __param_interval
        replacement: 5m
        action: replace
    - job_name: interval10m
      scrape_interval: 10m
      scrape_timeout: 1m
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
      - files:
        - ./servers/*10m.json
        refresh_interval: 5m
      relabel_configs:
      - source_labels: [instance]
        separator: ;
        regex: instance-(.*)
        target_label: __param_id
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __param_interval
        replacement: 10m
        action: replace
    - job_name: interval30m
      scrape_interval: 30m
      scrape_timeout: 1m
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
      - files:
        - ./servers/*30m.json
        refresh_interval: 5m
      relabel_configs:
      - source_labels: [instance]
        separator: ;
        regex: instance-(.*)
        target_label: __param_id
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __param_interval
        replacement: 30m
        action: replace
    - job_name: interval1h
      scrape_interval: 1h
      scrape_timeout: 5m
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
      - files:
        - ./servers/*1h.json
        refresh_interval: 5m
      relabel_configs:
      - source_labels: [instance]
        separator: ;
        regex: instance-(.*)
        target_label: __param_id
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __param_interval
        replacement: 1h
        action: replace
    - job_name: interval1d
      scrape_interval: 1d
      scrape_timeout: 5m
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
      - files:
        - ./servers/*1d.json
        refresh_interval: 5m
      relabel_configs:
      - source_labels: [instance]
        separator: ;
        regex: instance-(.*)
        target_label: __param_id
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __param_interval
        replacement: 1d
        action: replace
    - job_name: interval1s
      scrape_interval: 1s
      scrape_timeout: 1s
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
        - files:
            - ./servers/*1s.json
          refresh_interval: 5m
      relabel_configs:
        - source_labels: [instance]
          separator: ;
          regex: instance-(.*)
          target_label: __param_id
          replacement: $1
          action: replace
        - separator: ;
          regex: (.*)
          target_label: __param_interval
          replacement: 1s
          action: replace
    - job_name: interval3s
      scrape_interval: 3s
      scrape_timeout: 3s
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
        - files:
            - ./servers/*3s.json
          refresh_interval: 5m
      relabel_configs:
        - source_labels: [instance]
          separator: ;
          regex: instance-(.*)
          target_label: __param_id
          replacement: $1
          action: replace
        - separator: ;
          regex: (.*)
          target_label: __param_interval
          replacement: 3s
          action: replace
    - job_name: interval5s
      scrape_interval: 5s
      scrape_timeout: 5s
      metrics_path: /metrics
      scheme: http
      file_sd_configs:
        - files:
            - ./servers/*5s.json
          refresh_interval: 5m
      relabel_configs:
        - source_labels: [instance]
          separator: ;
          regex: instance-(.*)
          target_label: __param_id
          replacement: $1
          action: replace
        - separator: ;
          regex: (.*)
          target_label: __param_interval
          replacement: 5s
          action: replace