apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: monitor
    app.kubernetes.io/name: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/name: monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: monitor
        app.kubernetes.io/name: monitor
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: monitor
          image: {{ .Values.global.registry }}/{{ .Values.global.repository}}/{{ .Values.monitor.image.name }}:{{.Values.monitor.image.tag}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9002
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/devops/monitor/data
              name: v-pvc-bb-monitor
              subPath: data
            - mountPath: /opt/devops/monitor/rules
              name: v-pvc-bb-monitor
              subPath: rules
            - mountPath: /opt/devops/monitor/servers
              name: v-pvc-bb-monitor
              subPath: servers
            - mountPath: /opt/devops/monitor/monitor.yml
              name: v-monitor-cm
              subPath: monitor-yml
      restartPolicy: Always
      volumes:
        - name: v-pvc-bb-monitor
          persistentVolumeClaim:
            claimName: pvc-bb-monitor
        - name: v-monitor-cm
          configMap:
            name: monitor-cm
