apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: monitor
    app.kubernetes.io/name: monitor
spec:
  type: ClusterIP
  ports:
    - port: 9002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: monitor
    app.kubernetes.io/name: monitor
