apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-operator
  labels:
    app.kubernetes.io/name: mongo-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo-operator
      vendor: squids
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: mongo-operator
      labels:
        app.kubernetes.io/name: mongo-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
        vendor: squids
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: mongo-operator
      containers:
        - name: operator
          image: "{{ .Values.global.registry }}/{{.Values.global.repository}}/mongo-operator:{{ .Values.image.operator.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          env:
            - name: NOT_REGISTER_CRDS
              value: "true"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: logdir
              mountPath: /var/log/operator
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: logdir
          hostPath:
            path: /apps/logs/squids/operator/
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
