apiVersion: v1
data:
  config: |
    qfusionFlag: false
    clusterConfigs:
      - name: mongo
        version: 4.4
        storageClass: csi-qcfs
        images:
          - name: mongo
            image: mongo:4.4
          - name: mrs-manager
            image: swr.cn-east-2.myhuaweicloud.com/squids/mrs-manager:v1.0.0
          - name: restore
            image: swr.cn-east-2.myhuaweicloud.com/squids/mongo4.4-qfb:v1.0.0
          - name: exporter
            image: swr.cn-east-2.myhuaweicloud.com/squids/mongo-exporter:v1.0.0
          - name: backup
            image: swr.cn-east-2.myhuaweicloud.com/squids/mongo4.4-qfb:v1.0.0
kind: ConfigMap
metadata:
  name: mongo-app-config
  namespace: {{.Release.Namespace}}