apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-pod
  namespace: {{.Release.Namespace}}-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongo-pod
  namespace: {{.Release.Namespace}}-user
rules:
  - apiGroups:
      - mongo.woqutech.com
    resources:
      - mongoreplicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mongo-pod
  namespace: {{.Release.Namespace}}-user
subjects:
  - kind: ServiceAccount
    name: mongo-pod
    namespace: {{.Release.Namespace}}-user
roleRef:
  kind: Role
  name: mongo-pod
  apiGroup: rbac.authorization.k8s.io