apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-operator
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: mongo-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-operator
  namespace: {{.Release.Namespace}}-user
  labels:
    app.kubernetes.io/name: mongo-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongo-operator
  labels:
    app.kubernetes.io/name: mongo-operator
subjects:
  - kind: ServiceAccount
    name: mongo-operator
    namespace: {{.Release.Namespace}}
  - kind: ServiceAccount
    name: mongo-operator
    namespace: {{.Release.Namespace}}-user
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io



