apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-config-tmpl
    namespace: {{.Release.Namespace}}
data:
    prometheus.yaml.tmpl: |-
        global:
          scrape_interval: 5s
          evaluation_interval: 5s
          external_labels:
            cluster: prometheus-ha
            prometheus_replica: $(POD_NAME)
        alerting:
          # 告警配置文件
          alertmanagers:
            # 修改：使用静态绑定
            - static_configs:
                # 修改：targets、指定地址与端口
                - targets: ["alertmanager-headless:9093"]
        rule_files:
        - /etc/prometheus/rules/*rules.yaml
        scrape_configs:
        - job_name: kubernetes-apiservers
          scrape_interval: 1m
          scrape_timeout: 10s
          metrics_path: /metrics
          scheme: https
          kubernetes_sd_configs:
          - role: endpoints
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            separator: ;
            regex: default;kubernetes;https
            replacement: $1
            action: keep
        - job_name: cadvisor
          metrics_path: /metrics/cadvisor
          scrape_interval: 10s
          scrape_timeout: 10s
          scheme: https
          tls_config:
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
          - role: node
          relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__meta_kubernetes_node_address_InternalIP]
            action: replace
            target_label: __address__
            replacement: $1:10250
        - job_name: 'node'
          kubernetes_sd_configs:
          - role: node
          relabel_configs:
          - source_labels: [__meta_kubernetes_node_address_InternalIP]
            action: replace
            target_label: __address__
            replacement: $1:9100
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: node_name
          - source_labels: []
            action: replace
            target_label: name
            replacement: node_exporter
        - job_name: mysqld-exporter
          scrape_interval: 15s
          scrape_timeout: 10s
          metrics_path: /metrics
          scheme: http
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_db_type, __meta_kubernetes_pod_label_type]
            separator: ;
            regex: mysql;database
            replacement: $1
            action: keep
          - source_labels: [__address__]
            separator: ;
            regex: (.*)
            target_label: __address__
            replacement: mysqld-exporter:9104
            action: replace
          - source_labels: [__meta_kubernetes_pod_name]
            separator: ;
            regex: (.*)
            target_label: instance
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_namespace]
            separator: ;
            regex: (.*)
            target_label: namespace
            replacement: $1
            action: replace
          - separator: ;
            regex: __meta_kubernetes_pod_label_((app_name)|(db_role)|(db_type)|(type))
            replacement: $1
            action: labelmap
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app_name]
            separator: /
            regex: (.*)
            target_label: __param_secret
            replacement: ${1}-component-user-suffix
            action: replace
          - source_labels: [__meta_kubernetes_pod_ip]
            separator: ;
            regex: (.*)
            target_label: __param_ip
            replacement: ${1}
            action: replace
          - source_labels: [db_type]
            separator: ;
            regex: (mysql)
            target_label: alertingTargetType
            replacement: MySQLCluster
            action: replace
          - source_labels: [app_name]
            separator: ;
            regex: (.*)
            target_label: alertingTargetName
            replacement: $1
            action: replace
        - job_name: 'backup-exporter'
          scrape_interval: 1m
          scrape_timeout: 50s
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__address__]
            separator: ;
            regex: (.*)
            target_label: __address__
            replacement: backup-exporter:9100
            action: replace
        - job_name: 'redis-exporter'
          scrape_interval: 1m
          scrape_timeout: 50s
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            replacement: $1:9121
          - source_labels: [__meta_kubernetes_pod_label_db_type]
            separator: ;
            regex: (redis)
            replacement: $1
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            separator: ;
            regex: (.*)
            target_label: instance
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_namespace]
            separator: ;
            regex: (.*)
            target_label: namespace
            replacement: $1
            action: replace
        - job_name: 'mssql-exporter'
          scrape_interval: 1m
          scrape_timeout: 50s
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            replacement: $1:4000
          - source_labels: [__meta_kubernetes_pod_label_db_type]
            separator: ;
            regex: (mssql)
            replacement: $1
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            separator: ;
            regex: (.*)
            target_label: instance
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_namespace]
            separator: ;
            regex: (.*)
            target_label: namespace
            replacement: $1
            action: replace
        - job_name: 'volume-exporter'
          scrape_interval: 1m
          scrape_timeout: 50s
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            replacement: $1:9100
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            regex: volume-exporter
            action: keep
          metric_relabel_configs:
          - source_labels: [pod_name]
            target_label: instance
        - job_name: etcd-exporter
          scrape_interval: 20s
          scrape_timeout: 5s
          metrics_path: /metrics
          scheme: https
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_component]
              separator: ;
              regex: etcd
              replacement: $1
              action: keep
            - source_labels: [__meta_kubernetes_pod_host_ip]
              separator: ;
              regex: (.*)
              target_label: __address__
              replacement: $1:2379
              action: replace
          tls_config:
            ca_file: /etc/kubernetes/pki/etcd/ca.crt
            cert_file: /etc/kubernetes/pki/etcd/server.crt
            key_file: /etc/kubernetes/pki/etcd/server.key
---

apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-rules
    labels:
        name: prometheus-rules
    namespace: {{.Release.Namespace}}
data:
    alert-rules.yaml: |-
        groups:
        - name: k8s.rules
          rules:
          - expr: |
              sum(rate(container_cpu_usage_seconds_total{job="cadvisor", image!="", container!=""}[5m])) by (namespace)
            record: namespace:container_cpu_usage_seconds_total:sum_rate
          - expr: |
              sum(container_memory_usage_bytes{job="cadvisor", image!="", container!=""}) by (namespace)
            record: namespace:container_memory_usage_bytes:sum
          - expr: |
              sum by (namespace, pod, container) (
                rate(container_cpu_usage_seconds_total{job="cadvisor", image!="", container!=""}[5m])
              )
            record: namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
          - alert: node up
            expr: up{job="node"} == 0
            for: 150s
            annotations:
              summary: "Instance {{"{{"}}$labels.instance {{"}}"}} down"
              description: "{{"{{"}}$labels.instance {{"}}"}} of job {{"{{"}} $labels.job {{"}}"}} has been down for more than 150 seconds."
          - alert: kubernetes apiservers  up
            expr: up{job="kubernetes-apiservers"} == 0
            for: 15s
            annotations:
              summary: "Instance {{"{{"}}$labels.instance {{"}}"}} down"
              description: "{{"{{"}}$labels.instance {{"}}"}} of job {{"{{"}} $labels.job {{"}}"}} has been down for more than 15 seconds."
          - alert: etcd up
            expr: up{job="etcd-exporter"} == 0
            for: 15s
            annotations:
              summary: "Instance {{"{{"}}$labels.instance {{"}}"}} down"
              description: "{{"{{"}}$labels.instance {{"}}"}} of job {{"{{"}} $labels.job {{"}}"}} has been down for more than 15 seconds."
          - alert: backup-exporter up
            expr: up{job="backup-exporter"} == 0
            for: 15s
            annotations:
              summary: "Instance {{"{{"}}$labels.instance {{"}}"}} down"
              description: "{{"{{"}}$labels.instance {{"}}"}} of job {{"{{"}} $labels.job {{"}}"}} has been down for more than 15 seconds."
          - alert: Root Filesystem Usage
            expr: (node_filesystem_size_bytes{device="/dev/root"} - node_filesystem_free_bytes{device="/dev/root"}) / node_filesystem_size_bytes{device="/dev/root"} * 100 > 75
            for: 2m
            annotations:
              summary: "{{"{{"}}$labels.instance{{"}}"}}: High Filesystem usage detected"
              description: "{{"{{"}}$labels.instance{{"}}"}}: root Filesystem usage is above 75% (current value is: {{"{{"}}$value {{"}}"}}"
          - alert: SSD Filesystem Usage
            expr: (node_filesystem_size_bytes{device="/dev/mapper/squids--group-squids--data"} - node_filesystem_free_bytes{device="/dev/mapper/squids--group-squids--data"}) / node_filesystem_size_bytes{device="/dev/mapper/squids--group-squids--data"} * 100 > 80
            for: 2m
            annotations:
              summary: "{{"{{"}}$labels.instance{{"}}"}}: High Filesystem usage detected"
              description: "{{"{{"}}$labels.instance{{"}}"}}: SSD Filesystem usage is above 80% (current value is: {{"{{"}}$value {{"}}"}}"
          - alert: Node Memory Usage
            expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes )) / node_memory_MemTotal_bytes * 100 > 75
            for: 2m
            annotations:
              summary: "{{"{{"}}$labels.instance{{"}}"}}: High Memory usage detected"
              description: "{{"{{"}}$labels.instance{{"}}"}}: Memory usage is above 75% (current value is: {{"{{"}}$value {{"}}"}}"
          - alert: Node CPU Load
            expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{job="node",mode="idle"}[5m])) * 100)) > 80
            for: 5m
            annotations:
              summary: "{{"{{"}}$labels.instance{{"}}"}}: High CPU usage detected"
              description: "{{"{{"}}$labels.instance{{"}}"}}: CPU usage is above 80% (current value is: {{"{{"}}$value {{"}}"}}"
