apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bb-upload
  namespace: bb-system
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  selector:
    matchLabels:
      master-role: "master"