apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bb-monitor
  namespace: bb-system
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi