apiVersion: v1
kind: Service
metadata:
  name: ssh-exporter
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: ssh-exporter
    app.kubernetes.io/name: ssh-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9115
      targetPort: ssh-exporter
      protocol: TCP
      name: ssh-exporter
  selector:
    app.kubernetes.io/instance: ssh-exporter
    app.kubernetes.io/name: ssh-exporter