kind: Service
apiVersion: v1
metadata:
  name: clickhouse-exporter-metrics
  labels:
    clickhouse.altinity.com/chop:  {{ .Chart.AppVersion }}
    app: clickhouse-exporter
spec:
  ports:
    - port: 8888
      name: clickhouse-exporter-metrics
  selector:
    app: clickhouse-exporter