apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: bb-system
  name: pv-bb-upload
spec:
  capacity:
    storage: 40Gi
  hostPath:
    path: "/squids-data/local-path-provisioner/pvc-c6298a87-575d-464e-b752-7bd07cd06df6_bb-system_pvc-bb-upload"
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
