apiVersion: v1
kind: Service
metadata:
  name: {{ include "bbm.fullname" . }}
  namespace: bb-system
  labels:
    {{- include "bbm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bbm.selectorLabels" . | nindent 4 }}
