apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: backup-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{.Release.Namespace}}-user
  labels:
    app.kubernetes.io/name: backup-operator