apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: bb-system
data:
  nginx-conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
    #    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                      '$status $body_bytes_sent "$http_referer" '
    #                      '"$http_user_agent" "$http_x_forwarded_for"';

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" + "$request_body" '
                          '"$scheme" "$request_time" "$upstream_response_time" '
                          '"$http_user_agent" "$http_host" "$http_x_forwarded_for" "$content_length" '
                          '"$content_type" "$upstream_addr" "$upstream_status"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   36000;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        gzip on;
        gzip_min_length  5k;
        gzip_buffers     4 16k;
        #gzip_http_version 1.0;
        gzip_comp_level  5;
        gzip_types       text/plain application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
        gzip_vary        on;

        # Load modular configuration files from the /etc/nginx/conf.d directory.
        # See http://nginx.org/en/docs/ngx_core_module.html#include
        # for more information.
        # include /etc/nginx/conf.d/*.conf;
        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }

        server {
            listen          8888;
            listen          443 ssl http2 default_server;
            listen          [::]:443 ssl http2 default_server;
    #        server_name     bobingtech;
            server_name ok.dbsinan.com;
            root            /opt/devops/front;

            # rewrite ^(.*)$  https://$host$1 permanent;

            # SSL configuration
            include snippets/self-signed.conf;
            include snippets/ssl-params.conf;
            location / {
               #proxy_hide_header X-Frame-Options;
               add_header X-Frame-Options SAMEORIGIN always;
            }

            location /static/ {
              add_header X-Frame-Options SAMEORIGINi always;
            }
            location /upload/ {
              add_header X-Frame-Options SAMEORIGINi always;
              alias /opt/devops/upload/;
            }
            location /workspace/ {
                add_header X-Frame-Options SAMEORIGINi always;
                alias /opt/devops/pages/workspace/;
            }

            location ^~/bbm/v1/ {
                rewrite ^/bbm/v1/(.*)$ /v1/$1 break;
                proxy_pass http://bbm.bb-system.svc.cluster.local:9000;
                proxy_cookie_path / /bbm;
                proxy_connect_timeout 3600;
                proxy_read_timeout 3600;
                proxy_send_timeout 3600;
                send_timeout 3600;
            }

            location ^~/bbmws/v1/ {
                 rewrite ^/bbmws/v1/(.*)$ /v1/$1 break;
                 proxy_pass http://bbm.bb-system.svc.cluster.local:9000;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_http_version 1.1;
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection $connection_upgrade;
                 proxy_connect_timeout 36000;
                 proxy_read_timeout 36000;
                 proxy_send_timeout 36000;
                 send_timeout 36000;
             }

             location ^~/bomber/v1/ {
                 rewrite ^/bomber/v1/(.*)$ /v1/$1 break;
                 proxy_pass http://bbm.bb-system.svc.cluster.local:9000;
                 proxy_cookie_path / /bomber;
                 proxy_connect_timeout 3600;
                 proxy_read_timeout 3600;
                 proxy_send_timeout 3600;
                 send_timeout 3600;
             }

             location ^~/bomberws/v1/ {
                 rewrite ^/bomberws/v1/(.*)$ /v1/$1 break;
                 proxy_pass http://bbm.bb-system.svc.cluster.local:9000;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_http_version 1.1;
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection $connection_upgrade;
                 proxy_connect_timeout 36000;
                 proxy_read_timeout 36000;
                 proxy_send_timeout 36000;
                 send_timeout 36000;
             }

            location /bbm/dms/v1 {
                proxy_pass http://woqu-adapter.bb-system.svc.cluster.local:8999;
                proxy_cookie_path / /bbm;
                proxy_connect_timeout 3600;
                proxy_read_timeout 3600;
                proxy_send_timeout 3600;
                send_timeout 3600;
            }
        }
    }
  index-json: |
    {
        "LOGIN_URL":"",
        "NO_ACCESS_URL":""
    }

      