apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-operator
  labels:
    app.kubernetes.io/name: oracle-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: oracle-operator
      vendor: squids
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: oracle-operator
      labels:
        app.kubernetes.io/name: oracle-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
        vendor: squids
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: oracle-operator
      containers:
        - name: operator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /database-operator
          args:
            - --app-configmap-namespace={{ .Release.Namespace }}
            - --kubeconfig=/etc/kubeconf/config
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CURRENT_RUNTIME_ENV
              value: "{{ .Values.currentRuntimeEnv }}"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: kubeconf
              mountPath: /etc/kubeconf
            - name: logdir
              mountPath: /var/log/operator
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: kubeconf
          hostPath:
            path: /root/.kube
        - name: logdir
          hostPath:
            path: /apps/logs/squids/operator/
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}