kind: Service
apiVersion: v1
metadata:
  name: hubble-relay
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: hubble-relay
spec:
  type: ClusterIP
  selector:
    k8s-app: hubble-relay
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4245
