apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbm
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: bbm
    app.kubernetes.io/name: bbm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bbm
      app.kubernetes.io/name: bbm
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bbm
        app.kubernetes.io/name: bbm
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: bbm-client-file
          image: swr.cn-east-2.myhuaweicloud.com/squids/bbm-client-file:latest
          command: [ sh, -c, 'ls /client' ]
          volumeMounts:
            - name: v-bb-client
              mountPath: /client
      containers:
        - name: bbm
          image: {{ .Values.global.registry }}/{{ .Values.global.repository}}/{{ .Values.bbm.image.name }}:{{.Values.bbm.image.tag}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/devops/upload
              name: v-pvc-bb-upload
            - mountPath: /opt/devops/monitor/rules
              name: v-pvc-bb-monitor
              subPath: rules
            - mountPath: /opt/devops/monitor/servers
              name: v-pvc-bb-monitor
              subPath: servers
            - mountPath: /opt/devops/bbm.yaml
              name: v-bbm-cm
              subPath: bbm-yaml
            - mountPath: /opt/devops/client
              name: v-bb-client
      restartPolicy: Always
      volumes:
        - name: v-pvc-bb-upload
          persistentVolumeClaim:
            claimName: pvc-bb-upload
        - name: v-pvc-bb-monitor
          persistentVolumeClaim:
            claimName: pvc-bb-monitor
        - name: v-bbm-cm
          configMap:
            name: bbm-cm
        - name: v-bb-client
          emptyDir: { }
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
