apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres