apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  labels:
    app.kubernetes.io/name: mysql-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-operator
      vendor: squids
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: mysql-operator
      labels:
        app.kubernetes.io/name: mysql-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
        vendor: squids
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: mysql-operator
      containers:
        - name: operator
          image: {{ .Values.global.registry }}/{{.Values.global.repository}}/mysql-operator:{{include "operator.tag" .}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --enable-leader-election
            - --use-env-config
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DATABASE_IMAGE_PREFIX
              value: {{ .Values.global.registry }}/{{ .Values.global.repository }}/mysql
            - name: QFB_IMAGE_VERSION
              value: {{ .Values.image.qfbBackupTag }}
            - name: BACKUP_TRIGGER_IMAGE
              value: {{ .Values.global.registry }}/{{ .Values.global.repository }}/qfb-backup-job:{{ .Values.image.qfbBackupTag }}
            - name: QFB_IMAGE_PREFIX
              value: {{ .Values.global.registry }}/{{ .Values.global.repository }}/qfb-mysql
            - name: LEADER_IMAGE
              value: {{ .Values.global.registry }}/{{ .Values.global.repository }}/mysqlleader:{{.Values.image.leaderTag}}
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: logdir
              mountPath: /var/log/operator
        - name: apiserver
          image: {{ .Values.global.registry }}/{{.Values.global.repository}}/apiserver:{{include "apiserver.tag" .}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /apiserver
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUG
              value: "true"
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: logdir
          hostPath:
            path: /apps/logs/squids/operator/
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
