apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  labels:
    app.kubernetes.io/name: mysql-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-operator
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: mysql-operator
      labels:
        app.kubernetes.io/name: mysql-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: mysql-operator
      containers:
        - name: operator
          image: {{ .Values.global.registry }}/{{.Values.global.repository}}/{{.Values.image.name}}:{{include "operator.tag" .}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --enable-leader-election
          env:
            - name: NAMESPACE
              value: {{.Release.Namespace}}
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: logdir
              mountPath: /var/log/operator
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: logdir
          hostPath:
            path: /apps/logs/grds/operator/
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}