apiVersion: v1
data:
  maxscale.cnf: |2

    [maxscale]
    substitute_variables=true  #使配置支持环境变量
    threads={{$.Threads}}
    ms_timestamp=1             #timestamp精度
    syslog=1                   #将日志写入到syslog中
    maxlog=1                   #将日志写入到maxscale的日志文件中
    log_to_shm=0               #不将日志写入到共享缓存中，开启debug模式时可打开加快速度
    log_warning=1              #记录告警信息
    log_notice=1               #记录notice
    #log_info=1                 #记录info
    log_debug=0                #不打开debug模式
    log_augmentation=1         #日志递增
    admin_host=0.0.0.0


    {{- range $i, $v := .ServerLists}}
    [server-{{$i}}]
    type=server
    address={{$v.Server}}
    port=3306
    protocol=MariaDBBackend
    {{if $v.Weight}}serv_weight={{$v.Weight}}{{- end}}
    {{- end}}

    [MariaDB-Monitor]
    type=monitor
    module={{$.Module}}
    servers={{$.AllServer}}
    user=squidsRoot9527
    passwd=$MYSQL_ROOT_PASSWORD
    monitor_interval=1000


    [Read-Only-Service]
    type=service
    router=readconnroute
    servers={{$.AllServer}}
    user=squidsRoot9527
    passwd=$MYSQL_ROOT_PASSWORD
    enable_root_user=1
    weightby=serv_weight

    [Read-Write-Service]
    type=service
    router=readwritesplit
    servers={{$.AllServer}}
    user=squidsRoot9527
    passwd=$MYSQL_ROOT_PASSWORD
    enable_root_user=1
    master_accept_reads=true
    use_sql_variables_in=master
    weightby=serv_weight

    [MaxAdmin-Service]
    type=service
    router=cli

    [Read-Only-Listener]
    type=listener
    service=Read-Only-Service
    protocol=MariaDBClient
    port=4008
    {{if eq $.UseSSL "true"}}
    ssl=required
    ssl_cert=/etc/ssl/server-cert.pem
    ssl_key=/etc/ssl/server-key.pem
    ssl_ca_cert=/etc/ssl/ca-cert.pem
    {{ end }}


    [Read-Write-Listener]
    type=listener
    service=Read-Write-Service
    protocol=MariaDBClient
    port=4006
    {{if eq $.UseSSL "true"}}
    ssl=required
    ssl_cert=/etc/ssl/server-cert.pem
    ssl_key=/etc/ssl/server-key.pem
    ssl_ca_cert=/etc/ssl/ca-cert.pem
    {{ end }}


    [MaxAdmin-Listener]
    type=listener
    service=MaxAdmin-Service
    protocol=maxscaled
    socket=default
kind: ConfigMap
metadata:
  name: proxy-maxscale-template
  namespace: squids
