apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-exporter-cm
  namespace: bb-system
data:
  sql-exporter-yaml: |
    db:
      project: "bbm"
      driver: "postgres"
      name: "bobing"
      host: "postgres.bb-system.svc.cluster.local"
      port: "5432"
      user: "bobing"
      password: "bobing"
      charset: "utf8"
      ssl: "disable"
      debug: true
    log:
      level: "DEBUG"
      path: "../logs/"
      name: "sql_exporter.log"
      max_size: 128
      max_age: 7
      max_backups:  30
      to_console: true

    per_collect_timeout: 600

    recover_check_interval: 60

    http:
      timeout: 600
      dial_timeout: 10
      max_idle_conns_per_host: 1000
      max_conns_per_host: 1000
      idle_conn_timeout: 90

    bbc_server: "http://conn-pool.bb-system.svc.cluster.local:9006"
    exporter_config_server: "http://bbm.bb-system.svc.cluster.local:9000"
    telnet_ip_port:
      oracle: true
      mysql: false
      db2: true
      sqlserver: true
      postgresql: true
      informix: true
      dm: true
      shentong: true
      oceanbase: true
    redis:
      hostname: "redis.bb-system.svc.cluster.local"
      port: 6379
      password: ""
      database: 1  