apiVersion: v1
kind: Service
metadata:
  name: {{ include "sql-exporter.fullname" . }}
  namespace: bb-system
  labels:
    {{- include "sql-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: sql-exporter
      protocol: TCP
      name: sql-exporter
  selector:
    {{- include "sql-exporter.selectorLabels" . | nindent 4 }}
