{
 "title": "ClickHouse Proxy overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ckc",
    "label": "ckc",
    "query": {
     "query": "label_values(host_health{job=~\"chproxy-exporter\"},clickhouse_cluster)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(host_health{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\"},cluster)"
    }
   },
   {
    "name": "cluster_node",
    "query": {
     "query": "label_values(host_health{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\",cluster=~\"$cluster\"},cluster_node)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(request_sum_total{job=~\"chproxy-exporter\",clickhosue_cluster=~\"$ckc\"}[$interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(request_success_total{job=~\"chproxy-exporter\",clickhosue_cluster=~\"$ckc\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(request_duration_seconds{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(status_codes_total{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Summary request duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "60*sum(rate(request_duration_seconds_sum{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Limit Excess",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(concurrent_limit_excess_total{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Body size rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_body_bytes_total{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\"}[$interval]))",
     "legendFormat": "request"
    },
    {
     "expr": "sum(rate(response_body_bytes_total{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\"}[$interval]))",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "Cluster \"$cluster\" state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "cluster"
  },
  {
   "title": "Cluster \"$cluster\" host distirbution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster_node) (increase(request_sum_total{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\",cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "{{cluster_node}}"
    }
   ]
  },
  {
   "title": "Cluster \"$cluster\" concurrent queries by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(concurrent_queries{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\",cluster=~\"$cluster\"}) by (cluster_node)",
     "legendFormat": "{{cluster_node}}"
    }
   ]
  },
  {
   "title": "$cluster_node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 },
   "repeat": "cluster_node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(host_health{job=~\"chproxy-exporter\",clickhouse_cluster=~\"$ckc\",cluster=~\"$cluster\",cluster_node=~\"$cluster_node\"})",
     "legendFormat": "{{cluster_node}}"
    }
   ]
  }
 ]
}