{
 "title": "Clickhouse Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "exported_namespace",
    "label": "K8S Namespace",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime\"}, exported_namespace)"
    }
   },
   {
    "name": "chi",
    "label": "K8S Clickhouse Installation",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime\", exported_namespace=~\"$exported_namespace\"}, chi)"
    }
   },
   {
    "name": "hostname",
    "label": "Server",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime\",exported_namespace=~\"$exported_namespace\",chi=~\"$chi\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chi_clickhouse_clickhouse_up{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\", hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "CPU Time total",
   "type": "grafana-piechart-panel",
   "description": "The time which CPU spent on various types of activity total for the selected period",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "format": "µs",
   "valueName": "max",
   "targets": [
    {
     "expr": "increase(chi_clickhouse_event_UserTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "User Time {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_SystemTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "System Time {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSIOWaitMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "OS IO Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ThrottlerSleepMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Throttler Sleep {{hostname}}"
    }
   ]
  },
  {
   "title": " clickhouse-server Process Memory",
   "type": "graph",
   "description": "Memory size allocated for clickhouse-server process\nAvailable for ClickHouse 20.4+\n\nVIRT \nThe total amount of virtual memory used by the task. It includes all code, data and shared libraries plus pages that have been swapped out.\n\nVIRT = SWAP + RES\n\n\nSWAP -- Swapped size (kb)\nThe swapped out portion of a task's total virtual memory image.\n\nRES -- Resident size (kb)\nThe non-swapped physical memory a task has used.\nRES = CODE + USED DATA.\n\nCODE -- Code size (kb)\nThe amount of physical memory devoted to executable code, also known as the 'text resident set' size or TRS\n\nDATA -- Data+Stack size (kb)\nThe amount of physical memory allocated to other than executable code, also known as the 'data resident set' size or DRS.\n\nSHR -- Shared Mem size (kb)\nThe amount of shared memory used by a task. It simply reflects memory that could be potentially shared with other processes.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryCode{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "CODE {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryResident{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "RES {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryShared{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "SHR {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryDataAndStack{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "DATA {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryVirtual{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "VIRT {{ hostname }}"
    }
   ]
  },
  {
   "title": "Clickhouse Data size on Disk",
   "type": "graph",
   "description": "Total data size for all ClickHouse *MergeTree tables\n\n",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_DiskDataBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "graph",
   "description": "shows how much space available in the kubernetes pod\n\nbe careful with multiple volumes configuration, kubernetes volume claims and S3 as storage backend",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_DiskFreeBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"} / chi_clickhouse_metric_DiskTotalBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{ disk }} {{hostname}}"
    }
   ]
  },
  {
   "title": "Read（Mbytes）",
   "type": "graph",
   "description": "Show how much bytes read and decompress via compressed buffer on each server in cluster",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_CompressedReadBufferBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "uncompressed {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReadCompressedBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "compressed {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReadBufferFromFileDescriptorReadBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "file descriptor {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_OSReadBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "os {{hostname}}"
    }
   ]
  },
  {
   "title": "Bytes inserted",
   "type": "graph",
   "description": "## Tracks amount of inserted data.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_InsertedBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Insert bytes {{hostname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Show different types of connections for each server",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_TCPConnection{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "tcp {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_HTTPConnection{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "http {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_InterserverConnection{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "interserver {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_MySQLConnection{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "mysql {{hostname}}"
    }
   ]
  },
  {
   "title": "Rows Inserted",
   "type": "graph",
   "description": "## Tracks rows of inserted data.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_InsertedRows{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Insert rows {{hostname}}"
    }
   ]
  },
  {
   "title": "Select Queries",
   "type": "graph",
   "description": "Number of SELECT queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_SelectQuery{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "select {{hostname}}"
    }
   ]
  },
  {
   "title": "Insert Queries",
   "type": "graph",
   "description": "Number of INSERT queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_InsertQuery{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Insert queries {{hostname}}"
    }
   ]
  },
  {
   "title": "Merged Rows",
   "type": "graph",
   "description": "Show how intensive background merge processes",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_MergedRows{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "rows {{hostname}}"
    }
   ]
  },
  {
   "title": "Zookeeper Transactions",
   "type": "graph",
   "description": "Number of requests to ZooKeeper transactions per seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_ZooKeeperTransactions{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "transactions {{ hostname }}"
    }
   ]
  }
 ]
}