{
 "title": "Squids Mariadb Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "ins",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   },
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {
     "query": "label_values(backup_set_size_bytes, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"$ins\"}",
     "legendFormat": "instance_health"
    }
   ]
  },
  {
   "title": "CPU Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container=\"mysql\",pod=\"$ins\"}[5m]) / ignoring(cpu) (container_spec_cpu_quota / 100000)) * 100)",
     "legendFormat": "CPU_usage_ratio"
    }
   ]
  },
  {
   "title": "Memory Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((container_memory_rss{container=\"mysql\", pod=\"$ins\"}/container_spec_memory_limit_bytes)*100)",
     "legendFormat": "memory_usage_ratio"
    }
   ]
  },
  {
   "title": "DB Usage Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_filesystem_used_bytes{instance=\"$ins\"}/mysql_filesystem_size_bytes * 100",
     "legendFormat": "db_usage_ratio"
    }
   ]
  },
  {
   "title": "DB Space Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_filesystem_used_bytes{instance=\"$ins\"}",
     "legendFormat": "used"
    },
    {
     "expr": "mysql_filesystem_size_bytes{instance=\"$ins\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Backup Space Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(backup_set_size_bytes{cluster_name=\"$cluster_name\"})",
     "legendFormat": "backup_space_usage"
    }
   ]
  },
  {
   "title": "Connect Session",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=\"$ins\"}",
     "legendFormat": "total session"
    },
    {
     "expr": "mysql_global_status_threads_running{instance=\"$ins\"}",
     "legendFormat": "active session"
    }
   ]
  },
  {
   "title": "IO/Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{container=\"mysql\", pod=\"$ins\"}[5m])) + sum(rate(container_fs_reads_total{container=\"mysql\", pod=\"$ins\"}[5m]))",
     "legendFormat": "IO/Second"
    }
   ]
  },
  {
   "title": "Trans/Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=~\"(commit|rollback)\",instance=\"$ins\"}[5m]))",
     "legendFormat": "Trans/Second"
    }
   ]
  },
  {
   "title": "SQL/Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{instance=\"$ins\"}[5m]))",
     "legendFormat": "SQL/Second"
    }
   ]
  },
  {
   "title": "InnoDB Bytes Throughtput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_written{instance=\"$ins\"}[5m])) ",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_read{instance=\"$ins\"}[5m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "InnoDB Query Rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=~\"select\", instance=\"$ins\"}[5m]))",
     "legendFormat": "innoDB_query_rows"
    }
   ]
  },
  {
   "title": "DML SQL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert\", instance=\"$ins\"}[5m])",
     "legendFormat": "insert"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"delete\", instance=\"$ins\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert_select\", instance=\"$ins\"}[5m])",
     "legendFormat": "insert_select"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"replace\", instance=\"$ins\"}[5m])",
     "legendFormat": "replace"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"replace_select\", instance=\"$ins\"}[5m])",
     "legendFormat": "replace_select"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\", instance=\"$ins\"}[5m])",
     "legendFormat": "select"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\", instance=\"$ins\"}[5m])",
     "legendFormat": "update"
    }
   ]
  }
 ]
}