{
 "title": "Squids MongoDB Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "ins",
    "query": "label_values(mongodb_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"$ins\"}"
    }
   ]
  },
  {
   "title": "CPU Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container=\"mongod\",pod=\"$ins\"}[5m]) / ignoring(cpu) (container_spec_cpu_quota / 100000)) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((container_memory_rss{container=\"mongod\", pod=\"$ins\"}/container_spec_memory_limit_bytes)*100)"
    }
   ]
  },
  {
   "title": "Space Usage (Mbytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_dbstats_dataSize{instance=\"$ins\"}"
    },
    {
     "expr": "mongodb_dbstats_storageSize{instance=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connections{state=\"current\",instance=\"$ins\"})"
    },
    {
     "expr": "sum(mongodb_connections{state=~\"available|current\",instance=\"$ins\"})"
    }
   ]
  },
  {
   "title": "DML/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_op_counters_total{type=\"insert\",instance=\"$ins\"}"
    },
    {
     "expr": "mongodb_op_counters_total{type=\"update\",instance=\"$ins\"}"
    },
    {
     "expr": "mongodb_op_counters_total{type=\"delete\",instance=\"$ins\"}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_op_counters_total{type=\"query\",instance=\"$ins\"}"
    },
    {
     "expr": "mongodb_op_counters_total{type=\"getmore\",instance=\"$ins\"}"
    },
    {
     "expr": "mongodb_op_counters_total{type=\"command\",instance=\"$ins\"}"
    }
   ]
  }
 ]
}