{
 "title": "SQLServer Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "ins",
    "query": "label_values(mssql_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "SQLServer dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mssql_up{instance=\"$ins\"}"
    }
   ]
  },
  {
   "title": "CPU Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container=\"mssql\",pod=\"$ins\"}[5m]) / ignoring(cpu) (container_spec_cpu_quota / 100000)) * 100)",
     "legendFormat": "cpu_usage_ratio"
    }
   ]
  },
  {
   "title": "Memory Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((container_memory_rss{container=\"mssql\", pod=\"$ins\"}/container_spec_memory_limit_bytes)*100)",
     "legendFormat": "memory_usage_ratio"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_cache_hit_ratio{instance=\"$ins\"}",
     "legendFormat": "cache_hit_ratio"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_dm_exec_sessions{instance=\"$ins\",session_type=\"total_connections\"}",
     "legendFormat": "total"
    },
    {
     "expr": "mssql_dm_exec_sessions{instance=\"$ins\",session_type=\"session_activity\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "SQLserver Network Throughtput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "mssql_dm_os_performance_counters{counter_name=\"read_bytes_per_sec\",instance=\"$ins\"}",
     "legendFormat": "input"
    },
    {
     "expr": "mssql_dm_os_performance_counters{counter_name=\"write_bytes_per_sec\",instance=\"$ins\"}",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Performance Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mssql_dm_os_performance_counters{instance=\"$ins\"}[2m])",
     "legendFormat": "{{counter_name}}"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_volume_usage{instance=\"$ins\"}",
     "legendFormat": "{{volume_type}}"
    }
   ]
  },
  {
   "title": "Host Storage Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_host_storage_usage{instance=\"$ins\"}",
     "legendFormat": "{{driver}}"
    }
   ]
  }
 ]
}