{
 "title": "OpenGauss Overview",
 "tags": [
  "openGauss",
  "final"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "cluster", "query": { "query": "label_values(pg_up,cluster_id)" } },
   {
    "name": "ins",
    "label": "instance",
    "query": {
     "query": "label_values(pg_up{cluster_id=\"$cluster_name\"},instance)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info{target=\"$target\"},node_name)"
    }
   },
   {
    "name": "db",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*\",instance=\"$ins\"},datname)"
    }
   },
   {
    "name": "target",
    "label": "target",
    "query": {
     "query": "label_values(pg_up{cluster_id=\"$cluster_name\"},target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "系统CPU使用率",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{node_name=\"$node\",mode=\"system\"}[2m])) by (instance) *100",
     "legendFormat": "system"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{node_name=\"$node\",mode=\"iowait\"}[2m])) by (instance) *100",
     "legendFormat": "iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{node_name=\"$node\",mode=\"idle\"}[2m])) by (instance))*100",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_name=\"$node\"} - node_memory_MemAvailable_bytes{node_name=\"$node\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{node_name=\"$node\"}",
     "legendFormat": "可用"
    }
   ]
  },
  {
   "title": "运行状态",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{instance=\"$ins\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_run_times_run_time{instance=\"$ins\"}",
     "legendFormat": "run_time"
    }
   ]
  },
  {
   "title": "会话连接",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{instance=~\"$ins\"})",
     "legendFormat": "连接总数"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=~\"$ins\",state=\"active\"})",
     "legendFormat": "活动会话数"
    }
   ]
  },
  {
   "title": "每秒事务数",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{instance=\"$ins\"}[5m])) by (instance)",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{instance=\"$ins\"}[5m])) by (instance)",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "操作行数",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{instance=\"$ins\"}[5m])) by (instance)",
     "legendFormat": "tup_returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{instance=\"$ins\"}[5m])) by (instance)",
     "legendFormat": "tup_fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{instance=\"$ins\"}[5m])) by (instance)",
     "legendFormat": "tup_inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{instance=\"$ins\"}[5m])) by (instance)",
     "legendFormat": "tup_updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{instance=\"$ins\"}[5m])) by (instance)",
     "legendFormat": "tup_deleted"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "数据库空间",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=\"$ins\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "数据盘IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_now{node_name=\"$node\",device!~\"vda|dm-0\"}[5m])",
     "legendFormat": "iops"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{node_name=\"$node\",device!~\"vda|dm-0\"}[5m])",
     "legendFormat": "reads"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{node_name=\"$node\",device!~\"vda|dm-0\"}[5m])",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "网络吞吐",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{node_name=\"$node\",device=\"eth0\"}[5m])",
     "legendFormat": "receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{node_name=\"$node\",device=\"eth0\"}[5m])",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "同步延迟",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_replication_sent_diff{instance=\"$ins\"}",
     "legendFormat": "receive"
    },
    {
     "expr": "pg_stat_replication_replay_diff{instance=\"$ins\"}",
     "legendFormat": "replay"
    }
   ]
  }
 ]
}