{
 "title": "Squids Predixy Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "ins",
    "query": "label_values(predixy_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "predixy_up{instance=\"$ins\"}",
     "legendFormat": "instance_health"
    }
   ]
  },
  {
   "title": "CPU Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container=\"predixy\",pod=\"$ins\"}[5m]) / ignoring(cpu) (container_spec_cpu_quota / 100000)) * 100)",
     "legendFormat": "CPU_usage_ratio"
    }
   ]
  },
  {
   "title": "UsedMemory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "predixy_UsedMemory{instance=\"$ins\"}",
     "legendFormat": "used"
    },
    {
     "expr": "predixy_MaxMemory{instance=\"$ins\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "predixy_ClientConnections{type=\"insert\",instance=\"$ins\"}",
     "legendFormat": "client"
    },
    {
     "expr": "predixy_TotalRequests{type=\"update\",instance=\"$ins\"}",
     "legendFormat": "totalRequest"
    },
    {
     "expr": "predixy_TotalResponses{type=\"delete\",instance=\"$ins\"}",
     "legendFormat": "totalResponse"
    }
   ]
  }
 ]
}