{
 "title": "Squids Redis Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "ins",
    "query": "label_values(redis_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_up{instance=\"$ins\"}",
     "legendFormat": "instance_health"
    }
   ]
  },
  {
   "title": "CPU Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container=\"redis\",pod=\"$ins\"}[5m]) / ignoring(cpu) (container_spec_cpu_quota / 100000)) * 100)",
     "legendFormat": "CPU_usage_ratio"
    }
   ]
  },
  {
   "title": "Memory Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((container_memory_rss{container=\"redis\", pod=\"$ins\"}/container_spec_memory_limit_bytes)*100)",
     "legendFormat": "Memory_usage_ratio"
    }
   ]
  },
  {
   "title": "Cache Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=\"$ins\"}[5m])/ (irate(redis_keyspace_hits_total{instance=\"$ins\"}[5m]) + irate(redis_keyspace_misses_total{instance=\"$ins\"}[5m])) * 100",
     "legendFormat": "Cache_ratio"
    }
   ]
  },
  {
   "title": "Memory Fragmentation Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{instance=\"$ins\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Redis Network Throughtput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_instantaneous_input_kbps{instance=\"$ins\"}[5m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(rate(redis_instantaneous_output_kbps{instance=\"$ins\"}[5m]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_config_maxclients{instance=\"$ins\"}",
     "legendFormat": "total"
    },
    {
     "expr": "redis_connected_clients{instance=\"$ins\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Command Max Latency(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "redis_latency_max_spike_duration_seconds{instance=\"$ins\"} * 1000 ",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "Redis Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=\"$ins\"})",
     "legendFormat": "total keys"
    },
    {
     "expr": "redis_expired_keys_total{instance=\"$ins\"}",
     "legendFormat": "expired keys"
    },
    {
     "expr": "redis_evicted_keys_total{instance=\"$ins\"}",
     "legendFormat": "evicted keys"
    }
   ]
  },
  {
   "title": "OPS/Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_instantaneous_ops_per_sec{instance=\"$ins\"}",
     "legendFormat": "ops/second"
    }
   ]
  },
  {
   "title": "SET/GET/DEL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$ins\", cmd=\"set\"} [1m])) by (cmd)",
     "legendFormat": "set/second"
    },
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$ins\", cmd=\"get\"} [1m])) by (cmd)",
     "legendFormat": "get/second"
    },
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$instance\", cmd=\"del\"} [1m])) by (cmd)",
     "legendFormat": "del/second"
    }
   ]
  },
  {
   "title": "MSET/MGET",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$ins\", cmd=\"mset\"} [1m])) by (cmd)",
     "legendFormat": "mset/second"
    },
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$ins\", cmd=\"mget\"} [1m])) by (cmd)",
     "legendFormat": "mget/second"
    }
   ]
  },
  {
   "title": "HSET/HGET/HDEL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$ins\", cmd=\"hset\"} [1m])) by (cmd)",
     "legendFormat": "hset/second"
    },
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$ins\", cmd=\"hget\"} [1m])) by (cmd)",
     "legendFormat": "hget/second"
    },
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$instance\", cmd=\"hdel\"} [1m])) by (cmd)",
     "legendFormat": "hdel/second"
    }
   ]
  },
  {
   "title": "HMSET/HMGET",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$ins\", cmd=\"hmset\"} [1m])) by (cmd)",
     "legendFormat": "hmset/second"
    },
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$ins\", cmd=\"hmget\"} [1m])) by (cmd)",
     "legendFormat": "hmget/second"
    }
   ]
  }
 ]
}