global:
  registry: docker.io
  repository: squids

image:
  pullPolicy: IfNotPresent
  tag: v7.3.6.1

nodePort: 30001
monitorPort: 9090
replicasCount: 3
adminPassword: admin

enableHttps: true

#nodeSelector:
#  node-role.kubernetes.io/master: ""
#
#tolerations:
#  - effect: NoSchedule
#    key: node-role.kubernetes.io/master
#    operator: Exists

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: squids/cluster
              operator: In
              values:
                - squids-monitor
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: grafana
        topologyKey: kubernetes.io/hostname

resources: {}

