global:
  registry: docker.io
  repository: squids

image:
  pullPolicy: IfNotPresent
  tag: 7.3.6

nodePort: 30001
monitorPort: 9090
replicasCount: 3
adminPassword: admin

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: grafana
        topologyKey: kubernetes.io/hostname

resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "2048Mi"
    cpu: "1024m"

