global:
  registry: swr.cn-east-2.myhuaweicloud.com
  repository: squids
  imageName: grafana/grafana

image:
  pullPolicy: IfNotPresent
  tag: 8.1.3

nodePort: 30001
monitorPort: 9090
replicasCount: 1
adminPassword: admin

enableHttps: true

nodeSelector: {}
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "vpc.id"
              operator: In
              values:
                - "0"
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        preference:
          matchExpressions:
            - key: squids/cluster
              operator: In
              values:
                - squids-monitor
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: grafana
        topologyKey: kubernetes.io/hostname

resources: {}

loki:
  enabled: false
  port: 3100