apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-cluster-operator-global
  labels:
    app.kubernetes.io/name: kafka-operator
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: squids
roleRef:
  kind: ClusterRole
  name: strimzi-cluster-operator-global
  apiGroup: rbac.authorization.k8s.io
