apiVersion: v1
kind: Service
metadata:
  name: squids-redis-headless
  namespace: squids
  labels:
    app: squids-redis
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: squids-redis
