apiVersion: v1
kind: Service
metadata:
  name: squids-redis-headless
  namespace: {{.Release.Namespace}}
  labels:
    app: squids-redis
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: squids-redis
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}