apiVersion: apps/v1
kind: Deployment
metadata:
  name: squids-dts-api-server
  namespace: {{.Release.Namespace}}
  labels:
    app-name: squids-dts-api-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app-name: squids-dts-api-server
  template:
    metadata:
      labels:
        app-name: squids-dts-api-server
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        node-role.kubernetes.io/master: ""
      initContainers:
        - name: dts-proxy-files
          image: {{ .Values.image.dbmotionProxyFile.registry }}/{{ .Values.image.dbmotionProxyFile.repository }}/{{ .Values.image.dbmotionProxyFile.name }}:{{ .Values.image.dbmotionProxyFile.tag }}
          command: [ sh, -c, 'cp -r . /client_files/' ]
          volumeMounts:
            - name: dts-proxy-files
              mountPath: /client_files
      containers:
        - name: dts-api-server
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.image.dbmotionApiServer.registry }}/{{ .Values.image.dbmotionApiServer.repository }}/{{ .Values.image.dbmotionApiServer.name }}:{{ .Values.image.dbmotionApiServer.tag }}
          env:
            - name: SERVER_MODE
              value: "SAAS"
            - name: K8S_NAMESPACE
              value: "squids-user"
            - name: NODE_SELECTOR_KEY
              value: "squids/cluster"
            - name: NODE_SELECTOR_VALUE
              {{ if .Values.enableDbmotionNode }}
              value: "squids-dbmotion"
              {{ else }}
              value: "squids-master"
              {{ end }}
            - name: DBMOTION_IMAGE
              value: {{ .Values.image.dbmotion.registry }}/{{ .Values.image.dbmotion.repository }}/{{ .Values.image.dbmotion.name }}:{{ .Values.image.dbmotion.tag }}
            - name: MYSQL_HOST
              value: {{ .Values.mysql.host }}
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER_NAME
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: JWT_SECRET
              value: squids_secret_xz98fj9r1wq
            - name: ELASTICSEARCH_URI
              value: {{ .Values.es.url }}
            - name: PVC_CLAIM_NAME
              value: dbmotion-saas
            - name: MASTER_TOLERATION
              value: "y"
            - name: CPU_REQUEST
              value: "200m"
            - name: CPU_LIMIT
              value: "4"
            - name: MEMORY_REQUEST
              value: "100Mi"
            - name: MEMORY_LIMIT
              value: "8Gi"
            - name: DBMOTION_WEB_ADDR
              value: "http://squids-dts-api-server.{{.Release.Namespace}}.svc.cluster.local:{{.Values.image.dbmotionApiServer.httpPort}}"
            - name: DBMOTION_PUB_IP
              value: {{ .Values.dbmotion.public.ip }}
            {{ if .Values.enableMonitor }}
            - name: PHOENIX_ENDPOINT
              value: {{ .Values.phoenix.endpoint }}
            - name: OTHER_SYS_ENDPOINT
              value: {{ .Values.otherSys.endpoint }}
            {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.image.dbmotionApiServer.httpPort }}
            - name: grpc
              containerPort: {{ .Values.image.dbmotionApiServer.grpcPort }}
          volumeMounts:
            - name: timezone
              mountPath: /etc/timezone
            - name: localtime
              mountPath: /etc/localtime
            - mountPath: /dbmotion/log
              name: log-volume
            - name: dts-proxy-files
              mountPath: /client_files
      volumes:
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: log-volume
          persistentVolumeClaim:
            claimName: dbmotion-sass-log
        - name: dts-proxy-files
          emptyDir: { }
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbmotion-sass-log
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local-path
  volumeMode: "Filesystem"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
