# Default values for squids-hub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  pullPolicy: Always
  dbsServer:
    registry: swr.cn-east-2.myhuaweicloud.com
    repository: squids
    name: dbs-server
    tag: 2.0.0
  dbsApiServer:
    registry: swr.cn-east-2.myhuaweicloud.com
    repository: squids
    name: dbs-api-server
    tag: 2.0.0

rbac:
  # used by dbs-apiServer and dbs-server
  server:
    serviceAccount: server
    clusterRole: server
    clusterRoleBinding: server
  # used by dbs-agent
  agent:
    serviceAccount: agent
    clusterRole: agent
    clusterRoleBinding: agent

dbsInstallServer: http://121.40.140.155:8080