apiVersion: v1
kind: Service
metadata:
  name: woqu-adapter
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: woqu-adapter
    app.kubernetes.io/name: woqu-adapter
spec:
  type: NodePort
  ports:
    - name: woqu-adapter
      protocol: TCP
      port: 8999
      targetPort: 8999
      nodePort: 30450
  selector:
    app.kubernetes.io/instance: woqu-adapter
    app.kubernetes.io/name: woqu-adapter
