# Default values for backup-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
global:
  registry: docker.io
  repository: squids

tag: latest
image:
  pullPolicy: IfNotPresent
  qfbBackupTag: v1.0.0
  tag: v1.0.0
  operator:
    operator: v1.0.0

nodeSelector: {}
tolerations:
  - effect: NoSchedule
    key: squids/node
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: backup-operator
        topologyKey: kubernetes.io/hostname

# Deploy CRDs used by Logging Operator.
#
createCustomResource: true