apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-exporter
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: sql-exporter
    app.kubernetes.io/name: sql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sql-exporter
      app.kubernetes.io/name: sql-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sql-exporter
        app.kubernetes.io/name: sql-exporter
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sql-exporter
          image: {{ .Values.global.registry }}/{{ .Values.global.repository}}/{{ .Values.sqlExporter.image.name }}:{{.Values.sqlExporter.image.tag}}
          imagePullPolicy: Always
          ports:
            - name: sql-exporter
              containerPort: 9117
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/devops/exporter/sql_exporter.yaml
              name: v-sql-exporter-cm
              subPath: sql-exporter-yaml
      restartPolicy: Always
      volumes:
        - name: v-sql-exporter-cm
          configMap:
            name: sql-exporter-cm
