
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Values.clusterRole }}
rules:
- apiGroups:
  - backup.squids.io
  resources:
  - backuppolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.squids.io
  resources:
  - backuppolicies/finalizers
  verbs:
  - update
- apiGroups:
  - backup.squids.io
  resources:
  - backuppolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - backup.squids.io
  resources:
  - backupsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.squids.io
  resources:
  - backupsets/finalizers
  verbs:
  - update
- apiGroups:
  - backup.squids.io
  resources:
  - backupsets/status
  verbs:
  - get
  - patch
  - update
