apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-operator
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: backup-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-operator-rbac-{{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: backup-operator
subjects:
  - kind: ServiceAccount
    name: backup-operator
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
