
image:
  repository: swr.cn-east-2.myhuaweicloud.com/squids/prom/node-exporter
  pullPolicy: IfNotPresent
  tag: v1.0.0

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi