apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "mssql-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: {{ include "mssql-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}-user
