apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: redis
        app.kubernetes.io/name: redis
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: swr.cn-east-2.myhuaweicloud.com/squids/redis:6.2.5
          imagePullPolicy: Always
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
      restartPolicy: Always
