apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: bb-system
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
