
#namespace: kube-system

k8sServiceHost: ""
k8sServicePort: "6443"

agent:
  image:
    repository: swr.cn-east-2.myhuaweicloud.com/squids/mycilium
    tag: v1.10.8-vpc
    pullPolicy: IfNotPresent

operator:
  image:
    repository: docker.io/cilium/operator-generic
    tag: v1.10.3
    pullPolicy: IfNotPresent

hubble:
  relay:
    image:
      repository: docker.io/cilium/hubble-relay
      tag: v1.10.3
      pullPolicy: IfNotPresent
  ui:
    frontend:
      image:
        repository: quay.io/cilium/hubble-ui
        tag: v0.7.9
        pullPolicy: IfNotPresent
    backend:
      image:
        repository: quay.io/cilium/hubble-ui-backend
        tag: v0.7.9
        pullPolicy: IfNotPresent
envoy:
  image:
    repository: docker.io/envoyproxy/envoy
    tag: v1.18.2
    pullPolicy: IfNotPresent